using System;
using VContainer;
using VContainer.Unity;

public static class DungeonCharacterRegistration
{
    public static void RegisterDungeonCharacterSystems(
        this IContainerBuilder builder,
        CharacterSceneRuntimeReferences runtimeReferences)
    {
        if (builder == null)
        {
            throw new ArgumentNullException(nameof(builder));
        }

        builder.RegisterInstance(runtimeReferences
            ?? throw new ArgumentNullException(nameof(runtimeReferences)));
        builder.Register<ExperiencePacingApplicationAdapter>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<ExperiencePacingRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IExperiencePacingRuntime>();
        builder.RegisterEntryPoint<DungeonRunFlowRuntime>(Lifetime.Singleton)
            .As<IDungeonRunFlowRuntime>();
        builder.Register<RunVariableRuntimeReader>(Lifetime.Singleton)
            .As<IRunVariableRuntimeReader>()
            .As<IRunSeedProvider>()
            .As<ISurvivalPressureProvider>();
        builder.Register<ResourceRunCharacterCatalog>(Lifetime.Singleton)
            .As<IRunCharacterCatalog>();
        builder.Register<CharacterRuntimeProfileFactory>(Lifetime.Singleton)
            .As<ICharacterRuntimeProfileFactory>();
        builder.Register<CharacterNarrativeCatalog>(Lifetime.Singleton)
            .As<ICharacterNarrativeCatalog>();
        builder.Register<CharacterNarrativeRuntime>(Lifetime.Singleton)
            .As<ICharacterNarrativeQuery>()
            .As<ICharacterNarrativeCommand>()
            .As<ICharacterNarrativePersistence>();
        builder.Register<WorkerNarrativeQualificationQuery>(Lifetime.Singleton)
            .As<IWorkerNarrativeQualificationQuery>();
        builder.Register<TraitAnalysisCommandRuntime>(Lifetime.Singleton)
            .As<ITraitAnalysisCommand>();
        builder.Register<HeritableTraitEffectQuery>(Lifetime.Singleton)
            .As<IHeritableTraitEffectQuery>();
        builder.RegisterEntryPoint<CharacterTraitReactionRuntime>(Lifetime.Singleton)
            .As<ICharacterTraitReactionService>();
        builder.Register<CharacterCultureGameplayRuntime>(Lifetime.Singleton)
            .As<ICharacterCultureGameplayQuery>();
        builder.RegisterEntryPoint<CharacterNarrativeApplicationAdapter>(
            Lifetime.Singleton);
        builder.Register<V20StoryContentCatalog>(Lifetime.Singleton)
            .AsSelf()
            .As<ISocietyEventCatalog>()
            .As<IFactionStoryCatalog>()
            .As<IWorldEventCatalog>()
            .As<IEndingCatalog>();
        builder.Register<V20CampaignRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IV20CampaignPersistence>()
            .As<IRunMilestoneQuery>()
            .As<IMilestoneGameplayModifierQuery>()
            .As<IRunMilestoneCommand>()
            .As<ISeasonalEventQuery>()
            .As<ISocietyEventQuery>()
            .As<IContentWorkDelayQuery>()
            .As<IContentWorkDelayCommand>()
            .As<IFactionCampaignQuery>()
            .As<IFactionCampaignCommand>()
            .As<IEndlessCrisisCommand>();
        builder.Register<FacilityCapabilityQuery>(Lifetime.Singleton)
            .As<IFacilityCapabilityQuery>();
        builder.Register<ContentRequirementEvaluator>(Lifetime.Singleton)
            .As<IContentRequirementEvaluator>();
        builder.Register<V20ContentResolutionService>(Lifetime.Singleton)
            .As<IContentResolutionService>();
        builder.Register<V21ContentAlertChoiceActionDispatcher>(Lifetime.Singleton)
            .As<DungeonStory.Operation.IEventAlertChoiceActionDispatcher>();
        builder.Register<V20MilestoneWorldSnapshotProjector>(Lifetime.Singleton)
            .AsSelf()
            .As<IV20MilestoneWorldSnapshotQuery>();
        builder.RegisterEntryPoint<V20CampaignApplicationAdapter>(
            Lifetime.Singleton);
        builder.Register<ResourceCharacterSpeciesCatalog>(Lifetime.Singleton)
            .As<ICharacterSpeciesCatalog>()
            .As<ICharacterSpeciesDefinitionCatalog>()
            .As<ICharacterSpeciesEnvironmentCatalog>()
            .As<ICharacterLifeDefinitionCatalog>()
            .As<IReproductionDefinitionCatalog>();
        builder.Register<CharacterLifeRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterLifeQuery>()
            .As<ICharacterLifeCommand>()
            .As<ICharacterLifePersistence>();
        builder.RegisterEntryPoint<NarrativeAuthorityContextBootstrap>(
            Lifetime.Singleton);
        builder.Register<PhysicalAgeTreatmentRuntime>(Lifetime.Singleton)
            .As<IPhysicalAgeTreatmentService>()
            .As<ITemporalStasisMaintenanceService>();
        builder.Register<AgeTreatmentCommandRuntime>(Lifetime.Singleton)
            .As<IAgeTreatmentCommand>();
        builder.RegisterEntryPoint<TemporalStasisMaintenanceAdapter>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CharacterLifeApplicationAdapter>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CharacterLifeCelebrationAdapter>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CharacterAgeConditionBodyHealthAdapter>(
            Lifetime.Singleton);
        builder.Register<CharacterLifePublicationService>(Lifetime.Singleton)
            .As<ICharacterLifePublicationService>();
        builder.Register<KinshipHouseholdRuntime>(Lifetime.Singleton)
            .As<IKinshipQuery>()
            .As<IKinshipCommand>()
            .As<IHouseholdService>()
            .As<IKinshipHouseholdPersistence>();
        builder.Register<ReproductionRuntime>(Lifetime.Singleton)
            .As<IReproductionService>()
            .As<IReproductionPersistence>();
        builder.Register<ReproductionCommandRuntime>(Lifetime.Singleton)
            .As<IReproductionCommand>();
        builder.RegisterEntryPoint<ReproductionProposalAdapter>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<ReproductionApplicationAdapter>(
            Lifetime.Singleton);
        builder.Register<CareerRuntime>(Lifetime.Singleton)
            .As<ICareerService>()
            .As<ICareerPersistence>();
        builder.Register<CareerMentorshipService>(Lifetime.Singleton)
            .As<ICareerMentorshipService>();
        builder.RegisterEntryPoint<CareerApplicationAdapter>(Lifetime.Singleton);
        builder.Register<GriefTraumaRuntime>(Lifetime.Singleton)
            .As<IGriefTraumaService>()
            .As<IPsychosocialPersistence>();
        builder.Register<FestivalDefinitionCatalog>(Lifetime.Singleton)
            .As<IFestivalDefinitionCatalog>();
        builder.Register<CareerPositionDefinitionCatalog>(Lifetime.Singleton)
            .As<ICareerPositionDefinitionCatalog>();
        builder.Register<FuneralFestivalRuntime>(Lifetime.Singleton)
            .As<IFuneralFestivalService>()
            .As<IFestivalCommand>()
            .As<ISocialCareCommand>();
        builder.RegisterEntryPoint<CharacterDeathPopulationAdapter>(
            Lifetime.Singleton);
        builder.Register<ChildSafetyEnvironmentalProjection>(Lifetime.Singleton)
            .As<IChildSafetyEnvironmentalQuery>();
        builder.Register<ChildSafetyFilthProjection>(Lifetime.Singleton)
            .As<IChildSafetyFilthQuery>();
        builder.Register<WorldHazardZoneRuntime>(Lifetime.Singleton)
            .As<IWorldHazardZoneQuery>()
            .As<IWorldHazardOverlayCommand>();
        builder.Register<ChildSafetyPolicyRuntime>(Lifetime.Singleton)
            .As<IChildSafetyPolicy>();
        builder.Register<ChildSafetyGridTraversalCostPolicy>(Lifetime.Singleton)
            .As<IGridTraversalCostPolicy>();
        builder.RegisterEntryPoint<CombatHazardOverlayAdapter>(Lifetime.Singleton);
        builder.Register<ResourceDiseaseDefinitionCatalog>(Lifetime.Singleton)
            .As<IDiseaseDefinitionCatalog>();
        builder.Register<PopulationHealthRuntime>(Lifetime.Singleton)
            .As<IPopulationHealthService>()
            .As<IPopulationHealthQuery>()
            .As<IDiseaseSymptomEffectQuery>()
            .As<IPopulationHealthPersistence>();
        builder.Register<PhysicalVaccinationRuntime>(Lifetime.Singleton)
            .As<IPhysicalVaccinationService>();
        builder.Register<DiseaseFieldResponseRuntime>(Lifetime.Singleton)
            .As<IDiseaseFieldResponseCommand>();
        builder.RegisterEntryPoint<PopulationHealthApplicationAdapter>(Lifetime.Singleton);
        builder.Register<SpeciesIncidentHandlerRegistry>(Lifetime.Singleton)
            .As<ISpeciesIncidentHandlerRegistry>();
        builder.RegisterEntryPoint<CharacterSpeciesRuntime>(Lifetime.Singleton)
            .As<ICharacterSpeciesQuery>()
            .As<ICharacterSpeciesCommand>()
            .As<ICharacterSpeciesPersistence>();
        builder.Register<ResourceOwnerCandidateCatalog>(Lifetime.Singleton)
            .As<IOwnerCandidateCatalog>();
        builder.Register<RunStartVariableCatalog>(Lifetime.Singleton)
            .As<IRunStartVariableCatalog>();
        builder.Register<RunStartVariableSelector>(Lifetime.Singleton)
            .As<IRunStartVariableSelector>();
        builder.Register<CharacterVisualRootFactory>(Lifetime.Singleton)
            .As<ICharacterVisualRootFactory>();
        builder.Register<OwnerRunDataProvider>(Lifetime.Singleton)
            .As<IOwnerRunDataProvider>()
            .As<IOwnerRunManagerProvider>();
        builder.Register<OwnerCharacterFactory>(Lifetime.Singleton)
            .As<IOwnerCharacterFactory>();
        builder.Register<OwnerSelectionOptionButtonFactory>(Lifetime.Singleton)
            .As<IOwnerSelectionOptionButtonFactory>();
        builder.Register<OwnerRunLifecycleService>(Lifetime.Singleton)
            .As<IOwnerRunLifecycleService>();
        builder.Register<CharacterSpawnerProvider>(Lifetime.Singleton)
            .As<ICharacterSpawnerProvider>();
        builder.Register<CharacterSpawnObjectFactory>(Lifetime.Singleton)
            .As<ICharacterSpawnObjectFactory>();
        builder.Register<CharacterStatMaintenanceSceneAdapter>(Lifetime.Singleton)
            .As<DungeonStory.Characters.ICharacterStatMaintenancePort>();
        builder.Register<DungeonStory.Characters.CharacterStatMaintenanceRuntime>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<CharacterStatMaintenanceRuntimeAdapter>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<StaffDiscontentRuntimeService>(Lifetime.Singleton)
            .As<IStaffDiscontentRuntimeService>();
        builder.Register<DungeonWorkforceReplanService>(Lifetime.Singleton)
            .As<IWorkforceReplanService>()
            .As<IBuildingWorkforceReplanPort>();
        builder.Register<LocalLlmRuntimeProvider>(Lifetime.Singleton)
            .As<ILocalLlmRuntimeProvider>();
        builder.Register<ResourceCharacterSkillSystemSettingsProvider>(Lifetime.Singleton)
            .As<ICharacterSkillSystemSettingsProvider>();
        builder.Register<CharacterProgressionProfileProjector>(
            Lifetime.Transient);
        builder.Register<CharacterProgressionNotificationApplicationAdapter>(
            Lifetime.Singleton);
        builder.Register<CharacterStatsProjectionService>(Lifetime.Singleton);
        builder.Register<CharacterNeedStateService>(Lifetime.Singleton);
        builder.Register<CharacterMoodStateService>(Lifetime.Singleton);
        builder.Register<CharacterDeathEventFactory>(Lifetime.Singleton)
            .As<ICharacterDeathEventFactory>();
        builder.Register<CharacterStatsVitalsService>(Lifetime.Singleton);
        builder.Register<CharacterStatsMaintenanceSchedule>(Lifetime.Transient);
        builder.Register<CharacterPopulationApplicationAdapter>(Lifetime.Singleton);
        builder.Register<CharacterPopulationService>(Lifetime.Singleton)
            .As<ICharacterPopulationService>();
        builder.Register<PreparedStartPartyCharacterContext>(Lifetime.Singleton);
        builder.Register<PreparedStartPartyWorldContext>(Lifetime.Singleton);
        builder.Register<PreparedStartPartyGameplayApplier>(Lifetime.Singleton)
            .As<IPreparedStartPartyGameplayApplier>()
            .As<IPreparedStartPartyDiagnosticsQuery>();
        builder.Register<PreparedStartPartyCommitService>(Lifetime.Singleton)
            .As<IPreparedStartPartyCommitService>();
        builder.Register<StartPartyPreparationService>(Lifetime.Singleton)
            .As<IStartPartyPreparationService>();
        builder.RegisterEntryPoint<CharacterSkillGenerationService>(Lifetime.Singleton)
            .As<ICharacterSkillGenerationService>();
        builder.RegisterEntryPoint<CharacterSkillAutomaticTriggerRuntime>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<CharacterRecordTemplateBank>(Lifetime.Singleton);
        builder.Register<CharacterLogNarrativeService>(Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterLogNarrativeService>();
    }
}
