using VContainer;
using VContainer.Unity;

public static class DungeonCombatRegistration
{
    public static void RegisterDungeonCombatAndInvasion(
        this IContainerBuilder builder,
        InvasionSceneRuntimeReferences runtimeReferences,
        IPlayerCombatCommandSource playerCombatCommands)
    {
        builder.RegisterInstance(runtimeReferences);
        builder.RegisterInstance(playerCombatCommands)
            .As<IPlayerCombatCommandSource>();
        builder.Register<UnityCombatRandomSource>(Lifetime.Singleton)
            .As<ICombatRandomSource>();
        builder.Register<CombatResolutionService>(Lifetime.Singleton)
            .As<ICombatResolutionService>();
        builder.Register<CombatAffiliationService>(Lifetime.Singleton)
            .As<ICombatAffiliationService>();
        builder.Register<GridCombatLineOfSightService>(Lifetime.Singleton)
            .As<ICombatLineOfSightService>();
        builder.Register<GridCombatCoverQuery>(Lifetime.Singleton)
            .As<ICombatCoverQuery>();
        builder.Register<BuildingDestructiveLossRuntime>(Lifetime.Singleton)
            .As<IBuildingDestructiveLossRuntime>();
        builder.Register<CombatCoverDurabilityRegistry>(Lifetime.Singleton)
            .As<ICombatCoverDurabilityRegistry>()
            .As<IBuildingCoverDurabilityPort>();
        builder.Register<CombatFiringSolutionService>(Lifetime.Singleton)
            .As<ICombatFiringSolutionService>();
        builder.Register<ResourceAnatomyProfileCatalog>(Lifetime.Singleton)
            .As<IAnatomyProfileCatalog>();
        builder.Register<ResourceAnatomyConditionLexicon>(Lifetime.Singleton)
            .As<IAnatomyConditionLexicon>();
        builder.Register<ResourceCombatEquipmentCatalog>(Lifetime.Singleton)
            .As<ICombatEquipmentCatalog>();
        builder.Register<CombatCraftDefinitionCatalog>(Lifetime.Singleton)
            .As<ICombatCraftDefinitionCatalog>();
        builder.Register<CombatCraftFacilityEligibilityQuery>(Lifetime.Singleton)
            .As<ICombatCraftFacilityEligibilityQuery>();
        builder.Register<CombatRejectedRecoveryProjector>(Lifetime.Singleton)
            .As<ICombatRejectedRecoveryProjector>();
        builder.Register<ResourceEquipmentModuleCatalog>(Lifetime.Singleton)
            .As<IEquipmentModuleCatalog>();
        builder.Register<CombatEquipmentStatProjector>(Lifetime.Singleton);
        builder.Register<CombatEquipmentPhysicalStateWriter>(Lifetime.Singleton);
        builder.Register<CombatEquipmentRuntimeStateStore>(Lifetime.Singleton);
        builder.Register<EquipmentModulePreparedOutputBinder>(Lifetime.Singleton)
            .As<IFacilityBufferPlannedUniqueOutputBinder>();
        builder.Register<CombatEquipmentCraftOutputTransaction>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IProductionDomainOutputRestoreOwnerSource>()
            .As<IProductionDomainOutputFacilityLifecycleQuery>();
        builder.Register<CombatEquipmentLoadoutStore>(Lifetime.Singleton);
        builder.Register<EquipmentModuleInputOwnerRuntime>(Lifetime.Singleton)
            .As<IEquipmentModuleInputOwnerRuntime>();
        builder.RegisterEntryPoint<EquipmentModuleInputOwnerLifecycleRuntime>(
                Lifetime.Singleton)
            .As<IStartable>()
            .As<ITickable>()
            .As<IDungeonSaveCaptureGuard>();
        builder.Register<EquipmentModuleInputOwnerRestoreParticipant>(
                Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<EquipmentModuleRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IEquipmentModuleAppraisalRecovery>();
        builder.Register<EquipmentModuleAppraisalRestoreRecovery>(
                Lifetime.Singleton)
            .As<IDungeonSaveRestoreCompletedHook>();
        builder.Register<EquipmentHistoryTransferRuntime>(Lifetime.Singleton);
        builder.Register<LineageTransferCraftOperationContributor>(
                Lifetime.Singleton)
            .As<ICraftPersistentOperationContributor>();
        builder.Register<CombatEquipmentRuntimeCollaborators>(Lifetime.Singleton);
        builder.Register<CombatEquipmentCraftInputDestinationRuntime>(
                Lifetime.Singleton)
            .As<ICombatEquipmentCraftInputDestinationRuntime>();
        builder.Register<CombatEquipmentCraftingRuntime>(Lifetime.Singleton);
        builder.Register<CombatEquipmentCraftMaterialRestoreGuard>(
                Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<CombatEquipmentLoadoutRuntime>(Lifetime.Singleton);
        builder.Register<CombatEquipmentRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICombatEquipmentRuntime>()
            .As<ICombatEquipmentCraftQueueQuery>()
            .As<IBuildingEquipmentCraftingRuntimePort>()
            .As<ICombatLoadoutRuntime>()
            .As<ICombatEquipmentBurdenQuery>();
        builder.RegisterFactory<ICombatEquipmentCraftQueueQuery>(
            resolver => () => resolver.Resolve<ICombatEquipmentCraftQueueQuery>(),
            Lifetime.Singleton);
        builder.RegisterFactory<IBuildingEquipmentCraftingRuntimePort>(
            resolver => () => resolver.Resolve<
                IBuildingEquipmentCraftingRuntimePort>(),
            Lifetime.Singleton);
        builder.Register<RetailEquipmentAuthority>(Lifetime.Singleton)
            .As<IRetailEquipmentAuthority>();
        builder.Register<RetailStockPhysicalRuntime>(Lifetime.Singleton)
            .As<IRetailStockPhysicalRuntime>();
        builder.Register<CharacterTransientGameplayEffectSourceQuery>(Lifetime.Singleton)
            .As<ICharacterTransientGameplayEffectSourceQuery>();
        builder.Register<CharacterEquipmentGameplayEffectSourceQuery>(Lifetime.Singleton)
            .As<ICharacterEquipmentGameplayEffectSourceQuery>();
        builder.Register<CharacterDerivedStatsSnapshotProjector>(Lifetime.Singleton);
        builder.Register<EquipmentExpeditionRewardService>(Lifetime.Singleton)
            .As<IEquipmentExpeditionRewardService>();
        builder.Register<EquipmentEvolutionInputDeliveryGateway>(Lifetime.Singleton)
            .As<IEquipmentEvolutionInputDeliveryGateway>();
        builder.Register<EquipmentEvolutionInputOwnerRuntime>(Lifetime.Singleton)
            .As<IEquipmentEvolutionInputOwnerRuntime>();
        builder.Register<EquipmentEvolutionRuntime>(Lifetime.Singleton)
            .As<IEquipmentEvolutionRuntime>()
            .As<IEquipmentEvolutionPersistence>()
            .As<IAttunementRuntime>();
        builder.Register<EquipmentEvolutionMaterialRestoreGuard>(
                Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<EvolutionHistoryNarrativeRuntime>(
                Lifetime.Singleton)
            .As<IEvolutionHistoryNarrativeRuntime>();
        builder.Register<EvolutionCatalystEconomyRuntime>(Lifetime.Singleton)
            .As<IEvolutionCatalystEconomyRuntime>();
        builder.RegisterEntryPoint<EvolutionCatalystDropRuntime>(
                Lifetime.Singleton)
            .As<IEvolutionCatalystDropRuntime>();
        builder.RegisterEntryPoint<CombatEquipmentCharacterDeathConnector>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<EquipmentMaintenanceItemServices>(Lifetime.Singleton);
        builder.Register<EquipmentMaintenanceWorldServices>(Lifetime.Singleton);
        builder.Register<EquipmentMaintenanceClockServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<EquipmentMaintenancePolicyRuntime>(
                Lifetime.Singleton)
            .AsSelf()
            .As<ICombatEquipmentMaintenanceRuntime>()
            .As<ICombatEquipmentMaintenanceOrderQuery>()
            .As<ICombatEquipmentRepairTerminalEffectQuery>();
        builder.RegisterFactory<ICombatEquipmentMaintenanceOrderQuery>(
            resolver => () => resolver.Resolve<
                ICombatEquipmentMaintenanceOrderQuery>(),
            Lifetime.Singleton);
        builder.Register<EquipmentRepairMaterialRestoreGuard>(
                Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<CharacterBodyHealthRuntime>(
                Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterBodyHealthQuery>()
            .As<ICharacterBodyHealthCommand>()
            .As<ICharacterCombatSpecialStatusQuery>()
            .As<ICharacterManaQuery>()
            .As<ICharacterManaCommand>()
            .As<ICharacterBodyHealthPersistence>()
            .As<IAnatomyHealthRuntime>();
        builder.Register<SurgeryAggregateStateStore>(Lifetime.Singleton)
            .AsSelf()
            .As<ISurgeryOrderDemandQuery>();
        builder.RegisterEntryPoint<WildlifeAnatomyHealthRuntime>(
                Lifetime.Singleton)
            .As<IWildlifeAnatomyHealthRuntime>();
        builder.RegisterEntryPoint<SurgicalPatientTransportRuntime>(
                Lifetime.Singleton)
            .As<ISurgicalPatientTransportRuntime>();
        builder.Register<CharacterMedicalWorldServices>(Lifetime.Singleton);
        builder.Register<CharacterMedicalSupplyDestinationRuntime>(
                Lifetime.Singleton)
            .As<ICharacterMedicalSupplyDestinationRuntime>();
        builder.Register<CharacterMedicalSupplyDestinationDrainRuntime>(
                Lifetime.Singleton)
            .As<ICharacterMedicalSupplyDestinationDrainRuntime>();
        builder.RegisterEntryPoint<CharacterMedicalRuntime>(Lifetime.Singleton)
            .As<ICharacterMedicalQuery>()
            .As<ICharacterMedicalCommand>()
            .As<ICharacterMedicalPersistence>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ResourceSurgicalProcedureCatalog>(Lifetime.Singleton)
            .As<ISurgicalProcedureCatalog>();
        builder.Register<SurgicalFacilityQuery>(Lifetime.Singleton)
            .As<ISurgicalFacilityQuery>();
        builder.Register<SurgeryRiskEvaluator>(Lifetime.Singleton)
            .As<ISurgeryRiskEvaluator>();
        builder.Register<SurgeryEnvironmentRiskEvaluator>(
                Lifetime.Singleton)
            .As<ISurgeryEnvironmentRiskEvaluator>();
        builder.Register<SurgeryPolicyRuntime>(Lifetime.Singleton)
            .As<ISurgeryPolicyRuntime>();
        builder.Register<SurgeryExtractionLedger>(Lifetime.Singleton)
            .As<ISurgeryExtractionLedger>();
        builder.RegisterEntryPoint<SurgicalCorpseFreshnessRuntime>(
                Lifetime.Singleton)
            .As<ISurgicalCorpseFreshnessRuntime>();
        builder.RegisterEntryPoint<SurgicalPartRuntime>(Lifetime.Singleton)
            .As<ISurgicalPartRuntime>()
            .As<ISurgicalAugmentationQuery>();
        builder.Register<SurgicalPartProductionOutputHandler>(Lifetime.Singleton)
            .As<IProductionOutputHandler>()
            .As<IProductionOutputCapability>();
        builder.Register<SurgicalPartProductionOutputRestoreCapabilityValidator>(
                Lifetime.Singleton)
            .As<IProductionResolvedOutputRestoreCapabilityValidator>();
        builder.Register<SurgicalPartProductionOutputMaximumMassCapability>(
                Lifetime.Singleton)
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<SurgeryMaterialDestinationRuntime>(Lifetime.Singleton)
            .As<ISurgeryMaterialDestinationRuntime>();
        builder.Register<SurgeryMaterialTerminalRuntime>(Lifetime.Singleton)
            .As<ISurgeryMaterialTerminalRuntime>();
        builder.Register<HealSurgicalNodeEffectHandler>(Lifetime.Singleton)
            .As<ISurgicalProcedureEffectHandler>();
        builder.Register<MaintainSurgicalPartEffectHandler>(Lifetime.Singleton)
            .As<ISurgicalProcedureEffectHandler>();
        builder.Register<RemoveSurgicalNodeEffectHandler>(Lifetime.Singleton)
            .As<ISurgicalProcedureEffectHandler>();
        builder.Register<InstallSurgicalPartEffectHandler>(Lifetime.Singleton)
            .As<ISurgicalProcedureEffectHandler>();
        builder.Register<ApplySurgicalBurdenEffectHandler>(Lifetime.Singleton)
            .As<ISurgicalProcedureEffectHandler>();
        builder.Register<ReduceSurgicalBurdenEffectHandler>(Lifetime.Singleton)
            .As<ISurgicalProcedureEffectHandler>();
        builder.Register<ApplyAgeTreatmentEffectHandler>(Lifetime.Singleton)
            .As<ISurgicalProcedureEffectHandler>();
        builder.Register<SurgeryContentServices>(Lifetime.Singleton);
        builder.Register<SurgeryWorldServices>(Lifetime.Singleton);
        builder.Register<SurgeryResourceServices>(Lifetime.Singleton);
        builder.Register<SurgeryExecutionServices>(Lifetime.Singleton);
        builder.Register<SurgeryRestoreCoordinator>(Lifetime.Singleton)
            .AsSelf()
            .As<IDungeonRestoreTransactionParticipant>()
            .As<IDungeonSaveRestoreCompletedHook>();
        builder.RegisterEntryPoint<SurgeryRuntime>(Lifetime.Singleton)
            .As<ISurgeryQuery>()
            .As<ISurgeryWorkCommand>()
            .As<ISurgeryPersistence>()
            .As<ISurgeryCommandService>();
        builder.Register<DefenseTacticalWorldQueryAdapter>(Lifetime.Singleton)
            .As<IDefenseTacticalWorldQuery>();
        builder.RegisterEntryPoint<DefenseTacticalCoordinator>(
                Lifetime.Singleton)
            .As<IDefenseTacticalCoordinator>();
        builder.Register<CombatAttackPositionPlanner>(Lifetime.Singleton);
        builder.Register<CombatFallbackWeaponRuntimeAdapter>(Lifetime.Singleton)
            .As<ICombatFallbackWeaponRuntimePort>();
        builder.Register<CombatFallbackWeaponSelector>(Lifetime.Singleton);
        builder.Register<CombatCommandResultApplier>(Lifetime.Singleton);
        builder.Register<CombatCommandParticipantQuery>(Lifetime.Singleton);
        builder.Register<CharacterCombatCommandCombatServices>(Lifetime.Singleton);
        builder.Register<CombatCoverServices>(Lifetime.Singleton);
        builder.Register<CharacterCombatCommandWorldServices>(Lifetime.Singleton);
        builder.Register<CharacterCombatCommandCollaborators>(Lifetime.Singleton);
        builder.Register<CharacterCombatUiTextLocalizer>(Lifetime.Singleton)
            .As<ICharacterCombatUiTextQuery>();
        builder.Register<CharacterCombatStanceProjection>(Lifetime.Singleton)
            .As<ICharacterCombatStanceQuery>();
        builder.Register<CharacterCombatCommandRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterCombatCommandRuntime>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<CharacterCombatCommandUnityLifecycleAdapter>(
                Lifetime.Singleton)
            .AsSelf();
        builder.RegisterEntryPoint<CombatCommandBarUiController>(
                Lifetime.Singleton)
            .AsSelf();
        builder.RegisterEntryPoint<CombatTacticalOverlayPresenter>(
                Lifetime.Singleton)
            .As<ICombatTacticalOverlayPresenter>();
        builder.RegisterEntryPoint<CombatLoadoutPreparationRuntime>(
                Lifetime.Singleton)
            .AsSelf()
            .As<ICombatAmmoResupplyRuntime>()
            .As<ICombatEquipmentPickupRuntime>();

        builder.Register<ResourceFacilityCrimeSettingsProvider>(
                Lifetime.Singleton)
            .As<IFacilityCrimeSettingsProvider>();
        builder.Register<FacilityCrimeRiskEvaluator>(Lifetime.Singleton)
            .As<IFacilityCrimeRiskEvaluator>();
        builder.Register<InvasionThreatWorldSampler>(Lifetime.Singleton)
            .As<IInvasionThreatWorldSampler>();
        builder.Register<ResourceInvasionIntruderDataProvider>(
                Lifetime.Singleton)
            .As<IInvasionIntruderDataProvider>();
        builder.Register<InvasionIntruderContext>(Lifetime.Singleton)
            .As<IInvasionIntruderContext>();
        builder.Register<DefenseBreachPlanner>(Lifetime.Singleton)
            .As<IDefenseBreachPlanner>();
        builder.Register<DefenseRaidAwarenessRuntime>(Lifetime.Singleton)
            .As<IDefenseRaidAwarenessRuntime>();
        builder.Register<InvasionIntruderRuntimeFactory>(Lifetime.Singleton)
            .As<IInvasionIntruderFactory>();
        builder.Register<DefenseStatusRuntimeFactory>(Lifetime.Singleton)
            .As<IDefenseStatusRuntimeFactory>();
        builder.Register<DefenseStatusRuntimeService>(Lifetime.Singleton)
            .As<IDefenseStatusRuntimeService>();
        builder.Register<DefenseFacilityNetworkRuntime>(Lifetime.Singleton)
            .As<IDefenseFacilityNetworkRuntime>();
        builder.Register<DefenseFacilityInputOwnerBuildingSource>(
                Lifetime.Singleton)
            .As<IDefenseFacilityInputOwnerSource>();
        builder.Register<DefenseFacilityInputOwnerRuntime>(Lifetime.Singleton)
            .As<IDefenseFacilityInputOwnerRuntime>();
        builder.RegisterEntryPoint<DefenseFacilityInputOwnerLifecycleRuntime>(
                Lifetime.Singleton)
            .As<IDungeonSaveCaptureGuard>();
        builder.Register<DefenseFacilityRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IDefenseFacilityRuntime>();
        builder.Register<DefenseFacilityInputOwnerRestoreParticipant>(
                Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<DefenseFacilityPhysicalItemGateway>(Lifetime.Singleton)
            .As<IDefenseFacilityPhysicalItemGateway>();
        builder.Register<DefenseFacilityPhysicalRestoreGuard>(Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<DefenseFacilityPersistenceAdapter>(Lifetime.Singleton)
            .As<IDefenseFacilityPersistence>();
        builder.Register<BuildingStructuralIntegrityRuntime>(Lifetime.Singleton)
            .As<IBuildingStructuralIntegrityRuntime>();
        builder.Register<DefenseResponsePolicyRuntime>(Lifetime.Singleton)
            .As<IDefenseResponsePolicyRuntime>();
        builder.RegisterEntryPoint<InvasionOwnerEvacuationService>(
                Lifetime.Singleton)
            .As<IInvasionOwnerEvacuationService>();
        builder.Register<DefenseCombatSupportServices>(Lifetime.Singleton);
        builder.Register<DefenseCombatExecutor>(Lifetime.Singleton)
            .As<IDefenseCombatExecutor>();
        builder.Register<DefenseEngagementStore>(Lifetime.Singleton)
            .As<IDefenseEngagementStore>();
        builder.Register<DefenseEngagementWorldServices>(Lifetime.Singleton);
        builder.Register<DefenseEngagementCombatServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<DefenseEngagementRuntime>(
                Lifetime.Singleton)
            .As<IDefenseEngagementRuntime>();
        builder.RegisterEntryPoint<DungeonDefenseTimeResponseRuntime>(
                Lifetime.Singleton)
            .AsSelf();
    }

}
