using System;
using UnityEngine;
using VContainer;
using VContainer.Unity;

public static class DungeonPresentationRegistration
{
    public static void RegisterDungeonPresentation(
        this IContainerBuilder builder,
        Transform runtimeRoot,
        DungeonSceneRuntimeReferences sceneRuntimeReferences,
        IPlayerStaffCommandSource playerStaffCommands,
        RunResultPanel initialRunResultPanel)
    {
        if (builder == null)
        {
            throw new ArgumentNullException(nameof(builder));
        }

        if (runtimeRoot == null)
        {
            throw new ArgumentNullException(nameof(runtimeRoot));
        }

        builder.RegisterInstance(playerStaffCommands
                ?? throw new ArgumentNullException(nameof(playerStaffCommands)))
            .As<IPlayerStaffCommandSource>();
        builder.RegisterEntryPoint<CharacterPresentationScheduler>(
                Lifetime.Singleton)
            .As<ICharacterPresentationScheduler>();
        builder.RegisterEntryPoint<FacilityOperationalPresentationScheduler>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<OffensePanelFactory>(Lifetime.Singleton)
            .As<IOffensePanelFactory>();
        builder.Register<OffenseBattlePanelFactory>(Lifetime.Singleton)
            .As<IOffenseBattlePanelFactory>();
        builder.RegisterEntryPoint<OffenseBattleUiController>(Lifetime.Singleton)
            .AsSelf();
        builder.Register<OffensePanelButtonFactory>(Lifetime.Singleton)
            .As<IOffensePanelButtonFactory>();
        builder.Register<OffensePanelService>(Lifetime.Singleton)
            .As<IOffensePanelService>();
        builder.Register<OffenseRewardContextBuilder>(Lifetime.Singleton)
            .As<IOffenseRewardContextBuilder>();
        builder.Register<MetaRunResultBuilder>(Lifetime.Singleton)
            .As<IMetaRunResultBuilder>();
        builder.RegisterInstance(
                new RunResultPanelRegistry(initialRunResultPanel))
            .As<IRunResultPanelRegistry>();
        builder.Register<RunResultPanelFactory>(Lifetime.Singleton)
            .As<IRunResultPanelFactory>();
        builder.Register<RunResultTextLocalizer>(Lifetime.Singleton)
            .As<IRunResultTextQuery>();
        builder.Register<RunResultThemeApplicationAdapter>(Lifetime.Singleton)
            .As<IRunResultThemeQuery>();
        builder.Register<RunResultPanelService>(Lifetime.Singleton)
            .As<IRunResultPanelService>();
        builder.Register<CodexPanelFactory>(Lifetime.Singleton)
            .As<ICodexPanelFactory>();
        builder.Register<FacilitySynthesisPanelFactory>(Lifetime.Singleton)
            .As<IFacilitySynthesisPanelFactory>();
        builder.Register<FacilityEvolutionPanelFactory>(Lifetime.Singleton)
            .As<IFacilityEvolutionPanelFactory>();
        builder.Register<FacilityEvolutionPanelGateway>(Lifetime.Singleton)
            .As<IFacilityEvolutionPanelQuery>()
            .As<IFacilityEvolutionPanelCommand>();
        builder.Register<StaffWorkPriorityPanelUiFactory>(Lifetime.Singleton)
            .As<IStaffWorkPriorityPanelUiFactory>();
        builder.Register<StaffWorkPriorityPanelModelBuilder>(Lifetime.Singleton)
            .As<IStaffWorkPriorityPanelModelBuilder>();
        builder.Register<StaffWorkPriorityPanelFactory>(Lifetime.Singleton)
            .As<IStaffWorkPriorityPanelFactory>();
        builder.Register<P0FeatureSurfacePanelFactory>(Lifetime.Singleton)
            .As<IP0FeatureSurfacePanelFactory>();
        builder.Register<ResearchTreeWindowFactory>(Lifetime.Singleton)
            .As<IResearchTreeWindowFactory>();
        builder.Register<SurgeryClinicalContext>(Lifetime.Singleton);
        builder.Register<SurgeryExecutionContext>(Lifetime.Singleton);
        builder.Register<SurgerySubjectWorldContext>(Lifetime.Singleton);
        builder.Register<CharacterSurgeryWindowViewFactory>(Lifetime.Singleton)
            .As<ICharacterSurgeryWindowViewFactory>();
        builder.Register<SurgeryWindowPresentationContext>(Lifetime.Singleton);
        builder.Register<CharacterSurgeryWindowService>(Lifetime.Singleton)
            .As<ICharacterSurgeryWindowService>()
            .As<ISurgeryPlanningWindowService>()
            .As<ICharacterSurgeryWindowQuery>()
            .As<ICharacterSurgeryWindowCommand>();

        builder.Register<BuildingFeatureQueryService>(Lifetime.Singleton)
            .As<IBuildingFeatureQueryService>();
        builder.Register<BuildingFeatureCommandService>(Lifetime.Singleton)
            .As<IBuildingFeatureCommandService>();
        builder.Register<BuildingFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<ShopFeatureCommandService>(Lifetime.Singleton)
            .As<IShopFeatureCommandService>();
        builder.Register<ShopFeatureQueryService>(Lifetime.Singleton)
            .As<IShopFeatureQueryService>();
        builder.Register<ShopFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<WarehouseFeatureSessionContext>(Lifetime.Singleton);
        builder.Register<WarehouseFeatureWorldContext>(Lifetime.Singleton);
        builder.Register<WarehouseFeatureEconomyContext>(Lifetime.Singleton);
        builder.Register<WarehouseFeatureQueryService>(Lifetime.Singleton)
            .As<IWarehouseFeatureQueryService>();
        builder.Register<WarehouseCommandSessionContext>(Lifetime.Singleton);
        builder.Register<WarehouseCommandWorldContext>(Lifetime.Singleton);
        builder.Register<WarehouseCommandPlanningContext>(Lifetime.Singleton);
        builder.Register<WarehouseFeatureCommandService>(Lifetime.Singleton)
            .As<IWarehouseFeatureCommandService>();
        builder.Register<WarehouseFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<GameplayFlowDiagnosticsQuery>(Lifetime.Singleton)
            .As<IGameplayFlowDiagnosticsQuery>();
        builder.Register<OperationsSceneContext>(Lifetime.Singleton);
        builder.Register<OperationsWorldContext>(Lifetime.Singleton);
        builder.Register<OperationsStaffContext>(Lifetime.Singleton);
        builder.Register<OperationsFeatureQueryService>(Lifetime.Singleton)
            .As<IOperationsFeatureQueryService>();
        builder.Register<OperationsFeatureCommandService>(Lifetime.Singleton)
            .As<IOperationsFeatureCommandService>();
        builder.Register<CaptivityFeatureSectionPresenter>(Lifetime.Singleton)
            .As<ICaptivityFeatureSectionPresenter>();
        builder.Register<OperationsFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<DefenseThreatContext>(Lifetime.Singleton);
        builder.Register<DefenseOperationsContext>(Lifetime.Singleton);
        builder.Register<DefenseFacilityContext>(Lifetime.Singleton);
        builder.Register<DefenseFeatureQueryService>(Lifetime.Singleton)
            .As<IDefenseFeatureQueryService>();
        builder.RegisterEntryPoint<DefenseTacticalWorldOverlayController>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<DefenseFeatureCommandService>(Lifetime.Singleton)
            .As<IDefenseFeatureCommandService>();
        builder.Register<DefenseFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<ExpeditionFeatureQueryService>(Lifetime.Singleton)
            .As<IExpeditionFeatureQueryService>();
        builder.Register<ExpeditionFeatureCommandService>(Lifetime.Singleton)
            .As<IExpeditionFeatureCommandService>();
        builder.Register<ExpeditionFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<CodexFeatureQueryService>(Lifetime.Singleton)
            .As<ICodexFeatureQueryService>();
        builder.Register<CodexFeatureCommandService>(Lifetime.Singleton)
            .As<ICodexFeatureCommandService>();
        builder.Register<CodexFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<IndustrialPowerFluidContext>(Lifetime.Singleton);
        builder.Register<IndustrialTransportAutomationContext>(
            Lifetime.Singleton);
        builder.Register<IndustrialPresentationContext>(Lifetime.Singleton);
        builder.Register<IndustrialFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<FeatureSurfaceTabPresenterRegistry>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenterRegistry>();

        builder.Register<UITabGeneratedPanelFactory>(Lifetime.Singleton)
            .As<IUITabGeneratedPanelFactory>();
        builder.Register<UITabTopButtonFactory>(Lifetime.Singleton)
            .As<IUITabTopButtonFactory>();
        builder.Register<EventAlertButtonFactory>(Lifetime.Singleton)
            .As<IEventAlertButtonFactory>();
        builder.Register<EventAlertViewUiFactory>(Lifetime.Singleton)
            .As<IEventAlertViewUiFactory>();
        builder.Register<EventAlertViewPresenterFactory>(Lifetime.Singleton)
            .As<IEventAlertViewPresenterFactory>();
        builder.Register<EventAlertCanvasProvider>(Lifetime.Singleton)
            .As<IEventAlertCanvasProvider>()
            .As<IDungeonUiCanvasProvider>();
        builder.Register<FirstRunObjectiveProgressContext>(Lifetime.Singleton);
        builder.Register<FirstRunObjectivePresentationContext>(Lifetime.Singleton);
        builder.RegisterEntryPoint<FirstRunObjectiveRuntime>(Lifetime.Singleton)
            .As<IFirstRunObjectiveRuntime>();
        builder.RegisterEntryPoint<DungeonPlayerAutomationBridge>(Lifetime.Singleton)
            .AsSelf();
        builder.Register<NoticeFeedItemFactory>(Lifetime.Singleton)
            .As<INoticeFeedItemFactory>();
        builder.Register<NoticeFeedPresenter>(Lifetime.Singleton)
            .As<INoticeFeedPresenter>();
        builder.Register<DomainFailureLocalizer>(Lifetime.Singleton)
            .As<IDomainFailureLocalizer>()
            .As<IDefenseUiTextQuery>();
        builder.Register<CharacterNarrativeTextQuery>(Lifetime.Singleton)
            .As<ICharacterNarrativeTextQuery>();
        builder.Register<CharacterMedicalStatusLocalizer>(Lifetime.Singleton)
            .As<ICharacterMedicalStatusLocalizer>();
        builder.Register<OffenseWorldMapPanel.StrategicPresentationServices>(
            Lifetime.Singleton);
        builder.Register<CharacterSummaryRuntimeLogFactory>(Lifetime.Singleton)
            .As<ICharacterSummaryRuntimeLogFactory>();
        builder.Register<CharacterSummaryCombatPresenter>(Lifetime.Singleton);
        builder.Register<CharacterSummaryCaptivityPresenter>(Lifetime.Singleton);
        builder.Register<CharacterSummaryHealthPresenter>(Lifetime.Singleton);
        builder.Register<CharacterSummaryAiPresenter>(Lifetime.Singleton);
        builder.Register<CharacterSummaryGrowthPresenter>(Lifetime.Singleton);
        builder.Register<CharacterSummaryPopulationPresenter>(Lifetime.Singleton);
        builder.Register<CharacterSummaryStatusPresenter>(Lifetime.Singleton);
        builder.Register<CharacterSummaryShellPresenter>(Lifetime.Singleton);
        builder.Register<CharacterDetailedStatsRuntime>(Lifetime.Singleton)
            .As<ICharacterDetailedStatsRuntime>();
        _ = sceneRuntimeReferences
            ?? throw new ArgumentNullException(nameof(sceneRuntimeReferences));

        builder.Register<StaffWorkforceSceneAdapter>(Lifetime.Singleton)
            .AsSelf()
            .As<DungeonStory.Work.IStaffWorkforceSnapshotQuery>();
        builder.Register<DungeonStory.Work.StaffWorkforceRuntimeQueryService>(
            Lifetime.Singleton);
        builder.Register<StaffWorkforceRuntimeQueryServiceAdapter>(Lifetime.Singleton)
            .As<IStaffWorkforceQueryService>();
        builder.Register<WorkGridResolver>(Lifetime.Singleton)
            .As<IWorkGridResolver>();
        builder.Register<BuildingManagementWorldQueryAdapter>(Lifetime.Singleton)
            .As<IBuildingManagementWorldQuery>();
        builder.Register<BuildingManagementSummaryService>(Lifetime.Singleton)
            .As<IBuildingManagementSummaryService>();
        builder.Register<InvasionDefenseSummaryService>(Lifetime.Singleton)
            .As<IInvasionDefenseSummaryService>();
        builder.Register<OffenseTabSummaryService>(Lifetime.Singleton)
            .As<IOffenseTabSummaryService>();
        builder.Register<OperationTabSummaryService>(Lifetime.Singleton)
            .As<IOperationTabSummaryService>();
        builder.Register<ResearchCraftingSummaryService>(Lifetime.Singleton)
            .As<IResearchCraftingSummaryService>();
        builder.Register<CodexRecordSummaryApplicationAdapter>(Lifetime.Singleton)
            .As<ICodexRecordSummaryQueryPort>();
        builder.Register<CodexRecordSummaryService>(Lifetime.Singleton)
            .As<ICodexRecordSummaryService>();

        builder.Register<BuildingTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<StaffTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<ShopTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<WarehouseTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<OperationsTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<DefenseTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<ExpeditionTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<ResearchTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<CodexTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<IndustrialTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<UITabContentTextProvider>(Lifetime.Singleton)
            .As<IUITabContentTextProvider>();
        builder.Register<UiPopupService>(Lifetime.Singleton)
            .As<IUiPopupService>();
        builder.Register<DoorAccessPanelPresenter>(Lifetime.Singleton)
            .As<IDoorAccessPanelPresenter>();
        builder.Register<CircusBuildingPanelPresenter>(Lifetime.Singleton)
            .As<ICircusBuildingPanelPresenter>();
        builder.Register<EnvironmentalBuildingPanelPresenter>(
                Lifetime.Singleton)
            .As<IEnvironmentalBuildingPanelPresenter>();
        builder.Register<ProductionPanelOrderContext>(Lifetime.Singleton);
        builder.Register<ProductionPanelFacilityContext>(Lifetime.Singleton);
        builder.Register<ProductionUiTextLocalizer>(Lifetime.Singleton)
            .As<IProductionUiTextQuery>();
        builder.Register<ProductionPanelEnvironmentContext>(Lifetime.Singleton);
        builder.Register<ProductionBuildingPanelPresenter>(Lifetime.Singleton)
            .As<IProductionBuildingPanelPresenter>();
        builder.Register<EquipmentProgressionCommandPanel>(Lifetime.Singleton);
        builder.Register<EquipmentCraftingPanelPresenter>(Lifetime.Singleton)
            .As<IEquipmentCraftingPanelPresenter>();
        builder.Register<InstanceEvolutionPanelPresentation>(Lifetime.Singleton);
        builder.Register<InstanceEquipmentEvolutionSection>(Lifetime.Singleton);
        builder.Register<InstanceEvolutionPanelPresenter>(Lifetime.Singleton)
            .As<IInstanceEvolutionPanelPresenter>();
        builder.RegisterEntryPoint<FacilityRelocationTargetingService>(
                Lifetime.Singleton)
            .As<IFacilityRelocationTargetingService>();
        builder.Register<CropPlotBuildingPanelPresenter>(Lifetime.Singleton)
            .As<ICropPlotBuildingPanelPresenter>();
        builder.Register<AnimalHusbandryBuildingPanelPresenter>(
                Lifetime.Singleton)
            .As<IAnimalHusbandryBuildingPanelPresenter>();
        builder.Register<SurgeryBuildingPanelPresenter>(Lifetime.Singleton)
            .As<ISurgeryBuildingPanelPresenter>();
        builder.Register<PaidFacilityBuildingPanelPresenter>(
                Lifetime.Singleton)
            .As<IPaidFacilityBuildingPanelPresenter>();
        builder.Register<ServiceRoomBuildingPanelPresenter>(Lifetime.Singleton)
            .As<IServiceRoomBuildingPanelPresenter>();
        builder.Register<TreasuryDefenseBuildingPanelPresenter>(
                Lifetime.Singleton)
            .As<ITreasuryDefenseBuildingPanelPresenter>();
        builder.RegisterEntryPoint<CropPlotVisualPresenter>(Lifetime.Singleton)
            .AsSelf();
        builder.Register<TreasuryHudPresentationContext>(Lifetime.Singleton);
        builder.Register<TreasuryHudEconomyContext>(Lifetime.Singleton);
        builder.Register<TreasuryHudContractContext>(Lifetime.Singleton);
        builder.RegisterEntryPoint<TreasuryResourceHudController>(
                Lifetime.Singleton)
            .AsSelf();

        builder.RegisterComponentOnNewGameObject<ItemPileInfoPanel>(
                Lifetime.Singleton,
                nameof(ItemPileInfoPanel))
            .UnderTransform(runtimeRoot);
        builder.RegisterComponentOnNewGameObject<WildlifeInfoPanel>(
                Lifetime.Singleton,
                nameof(WildlifeInfoPanel))
            .UnderTransform(runtimeRoot);
        builder.Register<GameManagerFloatingIconFeedbackService>(Lifetime.Singleton)
            .As<IFloatingIconFeedbackService>();
    }
}
