using UnityEngine.SceneManagement;
using VContainer;
using VContainer.Unity;
using DungeonStory.Balance;

public static class DungeonWorldSimulationRegistration
{
    public static void RegisterDungeonWorldSimulation(
        this IContainerBuilder builder,
        Scene scopeScene,
        WorldSimulationSceneReferences sceneReferences)
    {
        builder.RegisterInstance(sceneReferences
            ?? throw new System.ArgumentNullException(nameof(sceneReferences)));
        builder.Register<WorldDropZoneQuery>(Lifetime.Singleton)
            .As<IWorldDropZoneQuery>();
        builder.Register<ExteriorIncidentActorService>(Lifetime.Singleton)
            .As<IExteriorIncidentActorService>();
        builder.Register<MerchantCartExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<InformantExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<ThiefExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<InjuredReturneeExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<PredatorApproachExteriorIncidentHandler>(Lifetime.Singleton)
            .AsSelf()
            .As<IExteriorIncidentHandler>();
        builder.Register<CargoDamageExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<ExteriorIncidentHandlerRegistry>(Lifetime.Singleton);
        builder.Register<ExteriorZoneWorldQuery>(Lifetime.Singleton)
            .As<IExteriorZoneQuery>();
        builder.Register<ExteriorActivityWorldServices>(Lifetime.Singleton);
        builder.Register<ExteriorActivityDomainServices>(Lifetime.Singleton);
        builder.Register<ExteriorActivityExecutionServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<ExteriorActivityRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IExteriorActivityRuntime>()
            .As<IExteriorPatrolRuntime>()
            .As<IExteriorIncidentRuntime>()
            .As<IExpeditionDepartureService>()
            .As<IExpeditionReturnService>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ResourceEconomyContentCatalog>(Lifetime.Singleton)
            .As<IResourceEconomyContentCatalog>();
        builder.Register<SurvivalContinuityCatalogQuery>(Lifetime.Singleton)
            .As<DungeonStory.Balance.ISurvivalContinuityCatalogQuery>();
        builder.RegisterDungeonGameContentCatalog();
        builder.Register<GameContentWasteProcessingRules>(Lifetime.Singleton)
            .As<IWasteProcessingRules>();
        builder.Register<AuthoredGameplayCatalog>(Lifetime.Singleton)
            .As<IMetaUpgradeDefinitionCatalog>()
            .As<IRunVariableDefinitionCatalog>()
            .As<IOwnerDoctrineDefinitionCatalog>()
            .As<IInvasionIntruderPatternDefinitionCatalog>()
            .As<ICharacterNeedDefinitionCatalog>()
            .As<ICharacterNeedDefinitionQuery>()
            .As<IStockCategoryDefinitionCatalog>()
            .As<IBuildingCategoryDefinitionCatalog>();
        builder.Register<RuntimeBuildingArchetypeCatalog>(Lifetime.Singleton)
            .As<IRuntimeBuildingArchetypeCatalog>();
        builder.Register<ResourceItemDefinitionCatalog>(Lifetime.Singleton)
            .As<IItemDefinitionCatalog>();
        builder.Register<ResourceDungeonItemCatalogProvider>(Lifetime.Singleton)
            .As<IDungeonItemCatalogProvider>();
        builder.Register<GenericDefinitionPhysicalItemMassProjector>(
                Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>()
            .As<IPhysicalItemDefinitionMassProjector>();
        builder.Register<CombatEquipmentPhysicalItemMassProjector>(
                Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>();
        builder.Register<ApparelPhysicalItemMassProjector>(Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>();
        builder.Register<WildlifeCarcassPhysicalItemMassProjector>(
                Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>();
        builder.Register<PackagedLotPhysicalItemMassProjector>(Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>();
        builder.Register<PhysicalItemMassQuery>(Lifetime.Singleton)
            .As<IPhysicalItemMassQuery>()
            .As<IPackagedLotDefinitionQuery>();
        builder.Register<PackagedLotTareOutputGateway>(Lifetime.Singleton)
            .As<IPackagedLotTareOutputGateway>();
        builder.Register<PackagedLotTareDispositionService>(Lifetime.Singleton)
            .As<IPackagedLotTareDispositionService>();
        builder.Register<ResourceItemHaulingSettingsProvider>(
                Lifetime.Singleton)
            .As<IItemHaulingSettingsProvider>();
        builder.Register<ItemMarkerPresenter>(Lifetime.Singleton)
            .As<IItemMarkerPresenter>();
        builder.Register<WorldItemRepository>(Lifetime.Singleton)
            .AsSelf()
            .As<IItemInstanceRepository>();
        builder.Register<FacilityBufferDestinationClaimRegistry>(Lifetime.Singleton)
            .AsSelf()
            .As<IFacilityBufferDestinationClaimQuery>()
            .As<IFacilityBufferDestinationClaimAuthorityQuery>()
            .As<IFacilityBufferDestinationClaimCommand>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<FacilityBufferPhysicalOccupancyQuery>(Lifetime.Singleton)
            .As<IFacilityBufferPhysicalOccupancyQuery>();
        builder.Register<FacilityBufferMassAdmissionService>(Lifetime.Singleton)
            .As<IFacilityBufferMassAdmissionService>()
            .As<IFacilityBufferMassCapacityQuery>()
            .As<IFacilityBufferMassCapacityAuthorityQuery>()
            .As<IFacilityBufferMassCapacityCommand>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<FacilityBufferPlannedOutputPublicationService>(
                Lifetime.Singleton)
            .As<IFacilityBufferPlannedOutputPublicationService>();
        builder.Register<FacilityOutputExactRouteService>(Lifetime.Singleton)
            .As<IFacilityOutputExactRoutePort>()
            .As<IFacilityOutputExactRouteOutboxQuery>()
            .As<IFacilityOutputExactRouteDeliveryOverlayParticipant>()
            .As<IFacilityOutputExactRouteOutboxPersistence>()
            .As<IFacilityOutputExactRouteRestoreReconciler>()
            .As<IPreparedOutputCheckpointGcParticipant>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<FacilityBufferDestinationLifecycleService>(Lifetime.Singleton)
            .As<IFacilityBufferDestinationLifecycleCommand>();
        builder.Register<FacilityBufferDestinationReleaseService>(Lifetime.Singleton)
            .As<IFacilityBufferDestinationReleaseService>();
        builder.Register<CharacterCarryInventoryRegistry>(Lifetime.Singleton)
            .As<ICharacterCarryInventoryRegistry>()
            .As<ICharacterSkillTransientStateRegistry>()
            .As<ICharacterRuntimeTransientStateRegistry>();
        builder.Register<PhysicalStockQuery>(Lifetime.Singleton)
            .As<IStockQuery>();
        builder.Register<WarehouseMassAdmissionService>(Lifetime.Singleton)
            .AsSelf()
            .As<IWarehouseMassAdmissionService>()
            .As<IWarehouseMassAdmissionLedgerQuery>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<WarehouseLifecycleOccupancyQuery>(Lifetime.Singleton)
            .As<IWarehouseLifecycleOccupancyQuery>();
        builder.Register<FloorClutterDiagnosticsQuery>(Lifetime.Singleton)
            .As<IFloorClutterDiagnosticsQuery>();
        builder.Register<ItemQuantityReservationService>(Lifetime.Singleton)
            .AsSelf()
            .As<IItemQuantityReservationService>()
            .As<IItemQuantityLeaseMutation>()
            .As<IItemQuantityReservationPersistence>()
            .As<IItemReservationMutationGate>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ItemReservationService>(Lifetime.Singleton)
            .As<IItemReservationService>();
        builder.Register<LeasedItemReservationService>(Lifetime.Singleton)
            .As<ILeasedItemReservationService>();
        builder.Register<AtomicItemConsumptionService>(Lifetime.Singleton)
            .As<IAtomicItemConsumptionService>();
        builder.Register<WorldItemSpawner>(Lifetime.Singleton)
            .As<IWorldItemSpawner>();
        builder.Register<PhysicalItemTransformService>(Lifetime.Singleton)
            .As<IPhysicalItemTransformService>();
        builder.Register<PhysicalItemRelocationService>(Lifetime.Singleton)
            .As<IPhysicalItemRelocationService>();
        builder.Register<PhysicalItemBatchDispositionService>(Lifetime.Singleton)
            .As<IPhysicalItemBatchDispositionService>()
            .As<IReservedPhysicalItemBatchDispositionService>()
            .As<ICarriedPhysicalItemBatchDispositionService>();
        builder.Register<ProductionPhysicalCustodyDrainOutbox>(Lifetime.Singleton)
            .As<IProductionPhysicalCustodyDrainOutbox>();
        builder.Register<ProductionInputDestinationCustodyDrainOutbox>(Lifetime.Singleton)
            .As<IProductionInputDestinationCustodyDrainOutbox>();
        builder.Register<ProductionInputDestinationCustodyDrainService>(Lifetime.Singleton)
            .As<IProductionInputDestinationCustodyDrainService>();
        builder.Register<ProductionCapacityRoutingDrainOutbox>(Lifetime.Singleton)
            .As<IProductionCapacityRoutingDrainOutbox>()
            .As<IProductionCapacityRoutingDrainQuery>();
        builder.Register<PhysicalFacilityItemSinkGateway>(Lifetime.Singleton)
            .As<IPhysicalFacilityItemSinkGateway>()
            .As<IPhysicalFacilityItemBatchSinkGateway>()
            .As<IPhysicalFacilityItemBatchTransferGateway>();
        builder.Register<PhysicalItemSourcePublicationService>(Lifetime.Singleton)
            .As<IPhysicalItemSourcePublicationService>();
        builder.Register<WorldItemQueryService>(Lifetime.Singleton)
            .AsSelf()
            .As<IWorldItemQueryService>();
        builder.Register<ProductionCapacityRoutingPhysicalSourceQuery>(
                Lifetime.Singleton)
            .As<IProductionCapacityRoutingPhysicalSourceQuery>();
        builder.Register<ProductionCapacityRoutingHaulPlanFence>(
                Lifetime.Singleton)
            .As<IProductionCapacityRoutingHaulPlanFence>();
        builder.Register<WorldItemHaulPlanningService>(Lifetime.Singleton)
            .As<IWorldItemHaulPlanningService>();
        builder.Register<ItemTransferService>(Lifetime.Singleton)
            .As<IItemTransferService>()
            .As<IReservedItemTransferService>()
            .As<IProductionCapacityRoutingActorQuiescence>();
        builder.Register<
                ProductionCapacityRoutingOperationAuthorityReleaseCoordinator>(
                Lifetime.Singleton)
            .As<IProductionCapacityRoutingOperationAuthorityReleaseCoordinator>();
        builder.RegisterEntryPoint<BufferStackAggregationService>(Lifetime.Singleton)
            .As<IBufferStackAggregationService>();
        builder.Register<WorldItemPersistenceService>(Lifetime.Singleton);
        builder.Register<WorldItemWarehouseService>(Lifetime.Singleton);
        // Shared admission participant for the live prepared-output delivery
        // coordinator and warehouse haul-planner authority validation.
        builder.Register<PreparedOutputExactDestinationAdmissionParticipant>(
                Lifetime.Singleton)
            .As<IPreparedOutputExactDestinationAdmissionParticipant>();
        builder.Register<WorldItemTheftService>(Lifetime.Singleton);
        builder.Register<WorldItemReadServices>(Lifetime.Singleton);
        builder.Register<WorldItemMutationServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WorldItemStackRuntime>(Lifetime.Singleton)
            .As<IWorldItemStackRuntime>()
            .As<IPhysicalItemRestoreStaging>()
            .As<IPhysicalItemRestoreCandidateQuery>()
            .As<IProductionInputDestinationCustodyDrainRestoreCandidateQuery>()
            .As<IPhysicalItemRestoreCandidateOutputQuery>()
            .As<IFacilityBufferPlannedOutputRestoreCandidateQuery>()
            .As<IFacilityOutputExactRouteRestoreCandidateQuery>()
            .As<IWarehouseOverCapacityEvacuationQuery>()
            .As<IEquipmentPhysicalItemGateway>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<BuildingItemStackPortAdapter>(Lifetime.Singleton)
            .As<IBuildingItemStackPort>();
        builder.Register<ResourceUsageIndex>(Lifetime.Singleton)
            .As<IResourceUsageIndex>()
            .As<IProductionDependencyCatalog>();
        builder.Register<ProductionItemGateway>(Lifetime.Singleton)
            .As<IProductionItemGateway>()
            .As<IProductionOutputBufferGateway>();
        builder.Register<ProductionStockSensorPhysicalGateway>(Lifetime.Singleton)
            .As<IProductionStockSensorPhysicalGateway>();
        builder.Register<ProductionStockSensorRemovalOutputGateway>(Lifetime.Singleton)
            .As<IProductionStockSensorRemovalOutputGateway>();
        builder.Register<ProductionWorkshopRuntime>(Lifetime.Singleton)
            .As<IProductionWorkshopRuntime>();
        builder.Register<ServiceRoomLinkRuntime>(Lifetime.Singleton)
            .As<IServiceRoomLinkRuntime>();
        builder.Register<ResourceServiceProcessCatalog>(Lifetime.Singleton)
            .As<IServiceProcessCatalog>();
        builder.Register<BlueprintServiceRoomResearchQuery>(Lifetime.Singleton)
            .As<IServiceRoomResearchQuery>();
        builder.Register<ServiceSessionRuntime.Dependencies>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<ServiceSessionRuntime>(Lifetime.Singleton)
            .As<IServiceSessionRuntime>()
            .As<ISurvivalServiceSessionCapability>()
            .As<IServiceAvailabilityQuery>()
            .As<IServiceDemandPolicyRuntime>();
        builder.Register<ProductionOutputPlanningService>(Lifetime.Singleton)
            .As<IProductionOutputPlanningService>();
        builder.Register<CanonicalProductionOutputResolver>(Lifetime.Singleton);
        builder.Register<ProductionPreparedOutputComponentCodec>(Lifetime.Singleton)
            .As<IProductionPreparedOutputComponentCodec>();
        builder.Register<ProductionMaximumOutputFactorCatalog>(Lifetime.Singleton)
            .As<IProductionMaximumOutputFactorCatalog>();
        builder.Register<ProductionOutputDestinationAuthorityRuntime>(
                Lifetime.Singleton)
            .As<IProductionOutputDestinationAuthorityRuntime>();
        builder.Register<ProductionFacilityMutationEpochRuntime>(Lifetime.Singleton)
            .AsSelf();
        builder.Register<ProductionFacilityDestructiveDrainOpenOperationQuery>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainOpenOperationQuery>();
        builder.Register<ProductionFacilityMutationAuthorityGate>(
                Lifetime.Singleton)
            .As<IProductionFacilityMutationEpochQuery>()
            .As<IProductionFacilityMutationEpochAuthority>();
        builder.Register<ProductionOutputBufferCapacityProjector>(
            Lifetime.Singleton);
        builder.Register<ProductionPreparedOutputRoutingAuthority>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputRoutingAuthority>()
            .As<IProductionPreparedOutputRoutingBatchQuery>()
            .As<IProductionPreparedOutputDeliveryRerouteParticipant>()
            .As<IProductionPreparedOutputRoutingPersistence>()
            .As<IProductionPreparedOutputRoutingRestoreReconciler>()
            .As<IPreparedOutputCheckpointGcParticipant>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ProductionPreparedOutputDeliveryCoordinator>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputDeliveryCoordinator>();
        builder.Register<ProductionPreparedOutputExactRouteLifecycle>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputExactRouteLifecycle>();
        builder.Register<ProductionCapacityRoutingDrainExecutionCoordinator>(
                Lifetime.Singleton)
            .As<IProductionCapacityRoutingDrainExecutionCoordinator>();
        builder.Register<ProductionPreparedOutputRoutingRestoreJoin>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputRoutingRestoreJoin>();
        builder.Register<ProductionPreparedOutputExecutionAdapter>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputExecutionPort>()
            .As<IProductionRuinedBatchExecutionPort>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ProductionPreparedOutputRestoreJoin>(Lifetime.Singleton)
            .As<IProductionPreparedOutputRestoreJoin>();
        builder.Register<ProductionFacilityDestructiveDrainStartPreflight>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainStartPreflight>();
        builder.Register<ProductionCycleUtilityService>(Lifetime.Singleton)
            .As<IProductionCycleUtilityService>();
        builder.Register<ProductionInputLogisticsService>(Lifetime.Singleton)
            .As<IProductionInputLogisticsService>();
        builder.Register<ProductionAssemblyBridgeAdapter>(Lifetime.Singleton)
            .As<IProductionAssemblyBridge>()
            .As<IProductionFacilityHandleQuery>();
        builder.Register<ProductionInputDestinationClaimRuntime>(Lifetime.Singleton)
            .As<IProductionInputDestinationClaimRuntime>();
        builder.Register<ProductionGenericBillTerminalDrainOutbox>(Lifetime.Singleton)
            .As<IProductionGenericBillTerminalDrainQuery>()
            .As<IProductionGenericBillTerminalDrainCommand>();
        builder.Register<ProductionAggregateStateStore>(Lifetime.Singleton);
        builder.Register<ProductionRecipeConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.Register<ProductionConstructionConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.Register<ProductionEquipmentConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.Register<ProductionSurgeryConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.Register<ResourceStockPolicyQuery>(Lifetime.Singleton)
            .As<IResourceStockPolicyQuery>();
        builder.Register<ProductionMarketSaleConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.RegisterEntryPoint<ProductionDistributionRuntime>(
                Lifetime.Singleton)
            .As<IProductionDistributionQuery>();
        builder.Register<ProductionBillOrderDependencies>(Lifetime.Singleton);
        builder.Register<ProductionBillExecutionDependencies>(Lifetime.Singleton);
        builder.Register<ProductionOutputExecutionService>(Lifetime.Singleton)
            .As<IProductionOutputExecutionService>();
        builder.Register<ProductionStockSensorRuntime>(Lifetime.Singleton)
            .As<IProductionStockSensorRuntime>();
        builder.Register<ProductionBillSnapshotProjector>(Lifetime.Singleton)
            .As<IProductionBillSnapshotProjector>();
        builder.RegisterEntryPoint<ProductionBillRuntime>(Lifetime.Singleton)
            .As<IProductionBillCoreQuery>()
            .As<IProductionFacilityDestructiveDrainPreparedOutputQuery>()
            .As<IProductionBillCoreOrderCommand>()
            .As<IProductionBillCoreWorkExecution>()
            .As<IProductionBillPersistence>();
        builder.Register<ProductionBillLifecycleContributor>(Lifetime.Singleton);
        builder.Register<CombatEquipmentCraftLifecycleContributor>(Lifetime.Singleton);
        builder.Register<ApparelWorkOrderLifecycleContributor>(Lifetime.Singleton);
        builder.Register<ProductionOutputCapacityRoutingLifecycleContributor>(
            Lifetime.Singleton);
        builder.Register<ProductionOutputPhysicalLifecycleContributor>(
            Lifetime.Singleton);
        builder.Register<ProductionOutputDestinationLifecycleQuery>(Lifetime.Singleton)
            .As<IProductionOutputDestinationLifecycleQuery>();
        builder.Register<ProductionFacilityMutationFence>(Lifetime.Singleton)
            .As<IProductionFacilityMutationFence>();
        builder.Register<ProductionBillSceneFacade>(Lifetime.Singleton)
            .As<IProductionBillQuery>()
            .As<IProductionBillOrderCommand>()
            .As<IProductionBillWorkExecution>();
        builder.Register<GrandProjectApplicationAdapter>(Lifetime.Singleton)
            .As<IGrandProjectWorldPort>()
            .As<IGrandProjectOperationsPort>();
        builder.RegisterEntryPoint<GrandProjectRuntime>(Lifetime.Singleton)
            .As<IGrandProjectRuntime>()
            .As<IGrandProjectBenefitQuery>();
        builder.Register<ResourceStockPolicyLogisticsDependencies>(Lifetime.Singleton);
        builder.Register<ResourceStockPolicyProductionDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<ResourceStockPolicyRuntime>(
                Lifetime.Singleton)
            .As<IResourceStockPolicyRuntime>();
        builder.Register<RegionalSupplyContractLogisticsDependencies>(Lifetime.Singleton);
        builder.Register<RegionalSupplyContractSessionDependencies>(Lifetime.Singleton);
        builder.Register<RegionalSupplyContractApplicationAdapter>(Lifetime.Singleton)
            .As<IRegionalSupplyContractWorldQuery>()
            .As<IRegionalSupplyContractCommandPort>()
            .As<IRegionalSupplyContractSessionPort>();
        builder.RegisterEntryPoint<RegionalSupplyContractRuntime>(
                Lifetime.Singleton)
            .As<IRegionalSupplyContractRuntime>();
        builder.Register<ResourceEconomyForecastInventoryDependencies>(Lifetime.Singleton);
        builder.Register<ResourceEconomyForecastPopulationDependencies>(Lifetime.Singleton);
        builder.Register<ResourceEconomyForecastPlanningDependencies>(Lifetime.Singleton);
        builder.Register<ResourceEconomyForecastService>(Lifetime.Singleton)
            .As<IResourceEconomyForecastService>();
        builder.Register<WasteProcessingInventoryPortAdapter>(Lifetime.Singleton)
            .As<IWasteProcessingInventoryPort>();
        builder.Register<WasteProcessingProductionPortAdapter>(Lifetime.Singleton)
            .As<IWasteProcessingProductionPort>();
        builder.Register<WasteProcessingMaterialDependencies>(Lifetime.Singleton);
        builder.Register<WasteProcessingOperationDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WasteProcessingRuntime>(Lifetime.Singleton)
            .As<IWasteProcessingQuery>()
            .As<IWastePolicyCommand>()
            .As<IWasteFeedCommand>()
            .As<IWasteFeedCandidateQuery>()
            .As<IWasteProcessingPersistence>();
        builder.Register<WorldFilthSpatialDependencies>(Lifetime.Singleton);
        builder.Register<WorldFilthGameplayDependencies>(Lifetime.Singleton);
        builder.Register<WorldFilthRuntimeDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WorldFilthRuntime>(Lifetime.Singleton)
            .As<IWorldFilthQuery>();
        builder.RegisterEntryPoint<WorldWaterRuntime>(Lifetime.Singleton)
            .As<IWorldWaterQuery>()
            .As<IWorldWaterContaminationCommand>();
        builder.Register<IndustrialInfrastructureTopologyRuntime>(
                Lifetime.Singleton)
            .As<IIndustrialInfrastructureTopologyRuntime>();
        builder.Register<AutomationPowerDemandRegistry>(Lifetime.Singleton)
            .AsSelf();
        builder.RegisterEntryPoint<ElectricalNetworkRuntime>(
                Lifetime.Singleton)
            .As<IPowerInfrastructureQuery>()
            .As<IPowerInfrastructureCommand>()
            .As<IPowerInfrastructurePersistence>();
        builder.RegisterEntryPoint<FluidNetworkRuntime>(Lifetime.Singleton)
            .As<IFluidInfrastructureQuery>()
            .As<IFluidInfrastructureCommand>()
            .As<IFluidInfrastructureTransaction>()
            .As<IManualWaterTransferTransaction>()
            .As<IFluidInfrastructureBatchTransaction>()
            .As<IFluidWastewaterTransaction>()
            .As<IFluidInfrastructurePersistence>();
        builder.Register<WaterFixtureUseRuntime>(Lifetime.Singleton)
            .As<IWaterFixtureUseRuntime>();
        builder.Register<ProcessFluidUseRuntime>(Lifetime.Singleton)
            .As<IProcessFluidUseRuntime>();
        builder.Register<ConveyorItemGateway>(Lifetime.Singleton);
        builder.RegisterEntryPoint<ConveyorRuntime>(Lifetime.Singleton)
            .As<IConveyorInfrastructureQuery>()
            .As<IConveyorInfrastructureCommand>()
            .As<IConveyorPayloadTransaction>()
            .As<IConveyorRestoreProjection>()
            .As<IConveyorRoutingService>();
        builder.Register<ConveyorPersistenceAdapter>(Lifetime.Singleton)
            .As<IConveyorInfrastructurePersistence>();
        builder.RegisterEntryPoint<AutomationRuntime>(Lifetime.Singleton)
            .As<IAutomationInfrastructureQuery>()
            .As<IAutomationInfrastructureCommand>()
            .As<IAutomationInfrastructurePersistence>();
        builder.Register<
                DungeonStory.Environment.EnvironmentalFieldAggregateStateStore>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<EnvironmentalFieldRuntimeApplicationAdapter>(
                Lifetime.Singleton)
            .As<IEnvironmentalFieldQuery>()
            .As<IEnvironmentalFieldCommand>()
            .As<IEnvironmentalFieldPersistence>();
        builder.Register<ResourceEnvironmentalWorkwearCatalog>(
                Lifetime.Singleton)
            .As<IEnvironmentalWorkwearCatalog>();
        builder.Register<ResourceApparelDefinitionCatalog>(Lifetime.Singleton)
            .As<IApparelDefinitionCatalog>();
        builder.Register<ResourceTextileMaterialCatalog>(Lifetime.Singleton)
            .As<ITextileMaterialCatalog>();
        builder.Register<ResourceMaterialEconomicProfileCatalog>(Lifetime.Singleton)
            .As<IMaterialEconomicProfileCatalog>();
        builder.Register<V27BalanceWorkCalculator>(Lifetime.Singleton)
            .As<IBalanceWorkCalculator>()
            .As<IRecipeBalanceWorkCalculator>();
        builder.Register<V23MaterialSalvageCalculator>(Lifetime.Singleton)
            .As<IMaterialSalvageCalculator>();
        builder.Register<DeterministicCraftQualityResolver>(Lifetime.Singleton)
            .As<ICraftQualityResolver>();
        builder.Register<TextileBatchCompactionService>(Lifetime.Singleton)
            .As<ITextileBatchCompactionService>();
        builder.Register<ApparelPhysicalTransaction>(Lifetime.Singleton)
            .As<IApparelPhysicalTransaction>();
        builder.Register<ApparelWorkOrderRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IApparelWorkOrderCommand>()
            .As<IApparelWorkOrderQuery>()
            .As<IApparelWorkOrderPersistence>()
            .As<IProductionApparelOrderTerminalEffectPort>()
            .As<IProductionApparelOrderSourceTerminalPort>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<CharacterEnvironmentAggregateStateStore>(
            Lifetime.Singleton);
        builder.Register<CharacterApparelAggregateStateStore>(Lifetime.Singleton);
        builder.Register<AnatomyAttachmentQuery>(Lifetime.Singleton)
            .As<IAnatomyAttachmentQuery>();
        builder.Register<ApparelMaterialProjector>(Lifetime.Singleton)
            .As<IApparelMaterialProjector>();
        builder.Register<ApparelAvailabilityIndex>(Lifetime.Singleton)
            .As<IApparelAvailabilityIndex>();
        builder.Register<CharacterApparelAggregate>(Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterApparelQuery>()
            .As<ICharacterApparelCommand>()
            .As<ICharacterApparelPersistence>();
        builder.Register<EquippedApparelPhysicalMassQuery>(Lifetime.Singleton)
            .As<IEquippedApparelPhysicalMassQuery>();
        builder.Register<EnvironmentalWorkwearRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IEnvironmentalWorkwearQuery>()
            .As<IEnvironmentalWorkwearCommand>()
            .As<IEnvironmentalWorkwearPersistence>();
        builder.Register<CharacterEnvironmentProtectionResolver>(
                Lifetime.Singleton)
            .As<ICharacterEnvironmentProtectionResolver>();
        builder.RegisterEntryPoint<CharacterEnvironmentUnityAdapter>(
                Lifetime.Singleton)
            .As<ICharacterEnvironmentStatusQuery>()
            .As<ICharacterEnvironmentExposureCommand>()
            .As<ICharacterEnvironmentWorkContext>()
            .As<ICharacterEnvironmentPersistence>();
        builder.Register<EnvironmentWorkPolicyUnityAdapter>(Lifetime.Singleton)
            .As<IEnvironmentWorkPolicy>();
        builder.Register<EnvironmentalWorkwearProductionOutputHandler>(
                Lifetime.Singleton)
            .As<IProductionOutputHandler>();
        builder.RegisterEntryPoint<IndustrialInfrastructureOverlayPresenter>(
                Lifetime.Singleton)
            .As<IIndustrialInfrastructureOverlayService>();
        if (SampleSceneRationRuntime.SupportsScene(scopeScene.name))
        {
            builder.RegisterEntryPoint<SampleSceneRationRuntime>(
                    Lifetime.Singleton)
                .AsSelf();
        }

        builder.Register<CharacterNeedBalanceRuntime>(Lifetime.Singleton)
            .As<ICharacterNeedBalanceRuntime>();
        builder.Register<CharacterDeprivationStateStore>(Lifetime.Singleton);
        builder.Register<CharacterPrimitiveSurvivalDependencies>(Lifetime.Singleton);
        builder.Register<CharacterDeprivationWorldDependencies>(Lifetime.Singleton);
        builder.Register<CharacterDeprivationSystemDependencies>(Lifetime.Singleton);
        builder.Register<CharacterDeprivationAuthorityDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CharacterDeprivationRuntime>(
                Lifetime.Singleton)
            .As<ICharacterDeprivationRuntime>()
            .As<ICharacterDeprivationQuery>()
            .As<ICharacterDeprivationCommand>()
            .As<ICharacterDeprivationIncidentSink>()
            .As<ICharacterDeprivationPersistence>();
        builder.Register<WorkOrderAggregateStateStore>(Lifetime.Singleton);
        builder.Register<WorkOrderExecutionServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WorkOrderRuntime>(Lifetime.Singleton)
            .As<IWorkOrderRuntime>()
            .As<IWorkOrderQuery>()
            .As<IWorkOrderWorkerPolicyQuery>()
            .As<IWorkOrderWorkerPolicyCommand>()
            .As<IQualityTargetPipelineQuery>()
            .As<IQualityTargetPipelineCommand>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ResourceWildlifeSpeciesCatalogProvider>(
                Lifetime.Singleton)
            .As<IWildlifeSpeciesCatalogProvider>();
        builder.RegisterEntryPoint<WildlifeHabitatMarkerRegistry>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeHabitatMarkerQuery>()
            .As<IWildlifeHabitatMarkerRegistry>();
        builder.Register<WildlifeOverlayRootPort>(Lifetime.Singleton)
            .As<IWildlifeOverlayRootPort>();
        builder.Register<WildlifeEcosystemApplicationPorts>(Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeEcosystemWorldPort>()
            .As<IWildlifeEcosystemPresentationPort>();
        builder.Register<WildlifeEcosystemRuntime>(Lifetime.Singleton)
            .AsSelf();
        builder.RegisterEntryPoint<WildlifeEcosystemApplicationAdapter>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeEcosystemRuntime>();
        builder.Register<WorldResourceEnvironmentPortAdapter>(Lifetime.Singleton)
            .As<IWorldResourceEnvironmentPort>();
        builder.Register<WorldResourceNodeHostPortAdapter>(Lifetime.Singleton)
            .As<IWorldResourceNodeHostPort>();
        builder.Register<WorldResourceOutputPortAdapter>(Lifetime.Singleton)
            .As<IWorldResourceOutputPort>();
        builder.Register<WorldResourceResearchPortAdapter>(Lifetime.Singleton)
            .As<IWorldResourceResearchPort>();
        builder.Register<WorldResourceEnvironmentDependencies>(Lifetime.Singleton);
        builder.Register<WorldResourceInfrastructureDependencies>(Lifetime.Singleton);
        builder.Register<WorldResourceProgressionDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WorldResourceRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IWorldResourceRuntime>()
            .As<IWorldResourcePersistence>();
        builder.Register<CropPlotWorldDependencies>(Lifetime.Singleton);
        builder.Register<CropPlotSimulationDependencies>(Lifetime.Singleton);
        builder.Register<PhysicalSeedLotGateway>(Lifetime.Singleton)
            .As<IPhysicalSeedLotGateway>();
        builder.Register<CropEcologyRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICropEcologyService>()
            .As<ICropEcologyPersistence>()
            .As<IInitialCropSeedGrant>();
        builder.Register<CertifiedSeedRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICertifiedSeedCommand>()
            .As<ICertifiedSeedPersistence>();
        builder.Register<CropPhysicalRestoreGuard>(Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<CertifiedSeedApplicationAdapter>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<CropSeedBootstrapRuntime>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CropPlotRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICropPlotRuntime>()
            .As<ICropPlotPersistence>();
        builder.Register<WildlifeCarcassService>(Lifetime.Singleton)
            .As<IWildlifeCarcassService>();
        builder.Register<WildlifeWorldServices>(Lifetime.Singleton);
        builder.Register<WildlifeCombatServices>(Lifetime.Singleton);
        builder.Register<WildlifeExecutionServices>(Lifetime.Singleton);
        builder.Register<WildlifeRestoreServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WildlifeRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeRuntime>()
            .As<IWildlifeQuery>()
            .As<IWildlifeHuntCommandService>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<WildlifeFoodRaidOutcomeTextLocalizer>(Lifetime.Singleton)
            .As<IWildlifeFoodRaidOutcomeTextQuery>();
        builder.Register<DungeonStory.CoreSession.ExternalInfluenceAggregateStateStore>(
            Lifetime.Singleton);
        builder.Register<ExternalInfluenceRuntimeApplicationAdapter.Dependencies>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<ExternalInfluenceRuntimeApplicationAdapter>(
                Lifetime.Singleton)
            .As<IExternalInfluenceRuntime>()
            .As<IExternalCombatInfluenceQuery>();
        builder.Register<SurvivalFoodRuntimeDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<SurvivalFoodRuntime>(Lifetime.Singleton)
            .As<ISurvivalFoodQuery>()
            .As<ISurvivalFoodCommand>()
            .As<ISurvivalFoodPersistence>()
            .As<ISurvivalFoodDebugCommand>()
            .As<ICharacterNutritionRuntime>()
            .As<ISurvivalEnvironmentQuery>()
            .As<ISurvivalStorageEnvironmentSink>();
        builder.RegisterEntryPoint<SurvivalEnvironmentalFieldBridge>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<CharacterConsumablesApplicationPorts>(Lifetime.Singleton)
            .As<ICharacterConsumablesWorldPort>()
            .As<ICharacterConsumablesInventoryPort>()
            .As<ICharacterConsumablesEventPort>()
            .As<ICharacterConsumablesWorkforcePort>();
        builder.Register<CharacterConsumablesRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterConsumablesApplication>()
            .As<ICharacterConsumablesPersistence>();
        builder.RegisterEntryPoint<CharacterConsumablesCompatibilityAdapter>(
                Lifetime.Singleton)
            .As<ICharacterConsumablesQuery>()
            .As<ICharacterConsumablesCommand>()
            .As<IFieldMealConsumptionCommand>()
            .As<ICharacterDietPolicyRuntime>()
            .As<IMealConsumptionRuntime>()
            .As<ICharacterMealOperationCancellation>()
            .As<ICharacterSubstanceRuntime>();
        builder.Register<CaptivityPersuasionHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityIsolationHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityCoercionHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityInterrogationHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityIndoctrinationHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityBrandingHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityBloodExtractionHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityMemoryExtractionHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityForcedModificationHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityCorruptionRitualHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityInteractionRegistry>(Lifetime.Singleton);
        builder.Register<CaptivityCharacterContext>(Lifetime.Singleton);
        builder.Register<CaptivityWorldContext>(Lifetime.Singleton);
        builder.Register<CaptivitySessionContext>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CaptivityRuntime>(Lifetime.Singleton)
            .As<ICaptivityRuntime>()
            .As<ICaptivityPersistence>()
            .As<ICaptiveLaborQuery>()
            .As<ICaptivityWorkReadinessQuery>()
            .As<ICaptivityCommandService>()
            .As<ICaptivityEscortRuntime>()
            .As<ICaptivityEscapeRuntime>()
            .As<ICharacterCarePriorityQuery>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<CaptivityRetaliationEffectsAdapter>(Lifetime.Singleton)
            .As<ICaptivityRetaliationEffectsPort>();
        builder.RegisterEntryPoint<CaptivityRetaliationRuntime>(Lifetime.Singleton)
            .AsSelf();
        builder.Register<WildlifeCaptureWorldContext>(Lifetime.Singleton);
        builder.Register<WildlifeCaptureCareContext>(Lifetime.Singleton);
        builder.Register<WildlifeCaptureSessionContext>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WildlifeCaptureRuntime>(Lifetime.Singleton)
            .As<IWildlifeCaptureRuntime>()
            .As<IWildlifeCaptureTransportRuntime>();
        builder.RegisterEntryPoint<AnimalHusbandryRuntime>(Lifetime.Singleton)
            .As<IAnimalHusbandryQuery>()
            .As<IAnimalHusbandryCommand>()
            .As<IAnimalHusbandryPersistence>()
            .As<IAnimalPenCompatibilityQuery>();
        builder.Register<NonlethalActCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<TrophyDisplayCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<DangerousStuntCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<CaptiveDuelCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<BeastShowCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<BeastArenaCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<PublicPunishmentCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<ExecutionPlayCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<PublicCorruptionRitualCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<CircusProgramRegistry>(Lifetime.Singleton);
        builder.Register<CircusProgramContext>(Lifetime.Singleton);
        builder.Register<CircusWorldContext>(Lifetime.Singleton);
        builder.Register<CircusCombatContext>(Lifetime.Singleton);
        builder.Register<CircusSessionContext>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CircusRuntime>(Lifetime.Singleton)
            .As<ICircusRuntime>()
            .As<ICircusPersistence>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<ItemStackViewToggleRuntime>(
                Lifetime.Singleton)
            .AsSelf();
        builder.RegisterEntryPoint<WildlifeEcosystemViewToggleRuntime>(
                Lifetime.Singleton)
            .AsSelf();
    }
}
