using DungeonStory.Infrastructure;
using VContainer;
using VContainer.Unity;

public static class DungeonSaveRegistration
{
    public static void RegisterDungeonSaveInfrastructure(
        this IContainerBuilder builder)
    {
        builder.Register<DungeonRuntimeAggregateRootStore>(Lifetime.Singleton);
        builder.Register<InvasionAggregateStateStore>(Lifetime.Singleton);
        builder.Register<CharacterWorldSpawnDependencies>(Lifetime.Singleton);
        RegisterSections(builder);
        builder.Register<DungeonSaveSectionRegistry>(Lifetime.Singleton)
            .As<IDungeonSaveSectionRegistry>();
        builder.Register<DungeonAggregateReferencePreflight>(Lifetime.Singleton)
            .As<IDungeonSavePreflightValidator>();
        builder.Register<DungeonGameSaveService>(Lifetime.Singleton)
            .As<IDungeonGameSaveService>();
        builder.Register<DungeonSaveSlotCatalog>(Lifetime.Singleton)
            .As<IDungeonSaveSlotCatalog>();
        builder.Register<DungeonSceneNavigator>(Lifetime.Singleton)
            .AsSelf()
            .As<IDungeonSceneNavigator>();
        builder.Register<DungeonGameSaveSlotService>(Lifetime.Singleton)
            .As<IDungeonGameSaveSlotService>();
        builder.RegisterEntryPoint<DungeonAutosaveService>(Lifetime.Singleton)
            .As<IDungeonSaveCommandService>();
        builder.Register<DungeonSaveUiPresentationContext>(Lifetime.Singleton);
        builder.Register<DungeonSaveUiSessionContext>(Lifetime.Singleton);
        builder.Register<DungeonSaveUiActionContext>(Lifetime.Singleton);
        builder.RegisterEntryPoint<DungeonSaveUiController>(Lifetime.Singleton)
            .AsSelf();
        builder.RegisterEntryPoint<DungeonGameplayLaunchController>(
                Lifetime.Singleton)
            .AsSelf();
    }

    private static void RegisterSections(IContainerBuilder builder)
    {
        builder.Register<RandomStreamSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<PhysicalItemsSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<PowerInfrastructureSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<FluidInfrastructureSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<ConveyorInfrastructureSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<WorkOrdersSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<ProductionBillsSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<ServiceRoomsSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<AutomationInfrastructureSaveSection>(
                Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<EnvironmentalFieldSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CharacterEnvironmentSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<SpeciesRuntimeSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<ExternalInfluenceSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<ResourceStockPolicySaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<RegionalSupplyContractSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<GrandProjectSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<WasteProcessingSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<WildlifeSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<WorldResourceSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CropPlotSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<SurvivalResourcesSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CharacterConsumablesSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<DarkSurvivalSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CharacterBodyHealthSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CombatEquipmentSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<EquipmentEvolutionSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CharacterMedicalSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<SurgerySaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<DefenseTacticalSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<DefenseFacilitySaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<EquipmentMaintenanceSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CharacterCombatCommandSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CaptivitySaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CircusSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<AnimalHusbandrySaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<ExteriorActivitySaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<OffenseAggregateSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<FactionSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<InvasionSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<OperatingDaySettlementSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<TreasuryEconomySaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<EventAlertSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<RunFlowSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<ExperiencePacingSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<DungeonDebugSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<BlueprintResearchSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<FacilityShopSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<RegularCustomerSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<StaffDiscontentSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CodexSaveApplicationAdapter>(Lifetime.Singleton)
            .As<ICodexSaveQueryPort>()
            .As<ICodexRestorePort>()
            .As<ICodexSaveSerializationPort>();
        builder.Register<CodexSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<RunVariableSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<MetaProgressionSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<ModularFacilityWorldSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
        builder.Register<CharacterWorldSaveSection>(Lifetime.Singleton)
            .As<IDungeonSaveSection>();
    }
}
