using VContainer;
using VContainer.Unity;

public static class DungeonWorkRegistration
{
    public static void RegisterDungeonWork(this IContainerBuilder builder)
    {
        RegisterWorkStatPolicies(builder);

        builder.Register<EmergencyWorkAccountingRuntime>(Lifetime.Singleton)
            .AsSelf()
            .AsImplementedInterfaces();
        builder.Register<SettlementAlertRuntime>(Lifetime.Singleton)
            .AsSelf()
            .AsImplementedInterfaces();
        builder.Register<EmergencyRiskForecastRegistry>(Lifetime.Singleton)
            .As<IEmergencyRiskForecastRegistry>();
        builder.RegisterEntryPoint<SettlementEmergencyReservePlanner>(
                Lifetime.Singleton)
            .As<ISettlementEmergencyReserveTargetQuery>();
        builder.RegisterEntryPoint<SettlementLaborAccountingRuntime>(
                Lifetime.Singleton)
            .As<ISettlementLaborAccountingService>()
            .As<ISettlementLaborPersistence>();
        builder.Register<SettlementThreatEventAdapter>(Lifetime.Singleton)
            .AsImplementedInterfaces();
        builder.Register<ProjectWorkforceRuntime>(Lifetime.Singleton)
            .As<IProjectWorkforceRuntime>();

        builder.Register<RepairWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<ResearchWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>();
        builder.Register<BuildingCraftWorkRuntimeAdapter>(Lifetime.Singleton)
            .As<IBuildingCraftWorkRuntimePort>();
        builder.Register<CraftWorkExecutionHandler>(Lifetime.Singleton);
        builder.Register<CraftWorkExecutionAdapter>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>();
        builder.Register<ButcherWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<SurvivalWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<CleanWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>();
        builder.Register<WardenWorkExecutionUnityAdapter>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.RegisterFactory<ICircusRuntime>(
            resolver => () => resolver.Resolve<ICircusRuntime>(),
            Lifetime.Singleton);
        builder.Register<PerformWorkExecutionUnityAdapter>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<ResourceGatheringWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<AnimalHusbandryWorkRuntimePortAdapter>(Lifetime.Singleton)
            .As<IAnimalHusbandryWorkRuntimePort>();
        builder.Register<AnimalHusbandryWorkExecutionHandler>(Lifetime.Singleton);
        builder.Register<AnimalHusbandryWorkExecutionAdapter>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<GrandProjectWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<SurgeryWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<ThreatMitigationWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<PlumbingWorkExecutionHandler>(Lifetime.Singleton)
            .As<IWorkExecutionHandler>()
            .As<IWorkCandidateProvider>()
            .As<IWorkUrgencyProvider>();
        builder.Register<WorkExecutionHandlerRegistry>(Lifetime.Singleton)
            .As<IWorkExecutionHandlerRegistry>()
            .As<IWorkPolicyRegistry>();
        builder.Register<WorkStatPolicyRegistry>(Lifetime.Singleton)
            .As<IWorkStatPolicyRegistry>();
        builder.Register<WorkAmountCalculator>(Lifetime.Singleton)
            .As<IWorkAmountCalculator>();
        builder.Register<EligibleWorkerQuery>(Lifetime.Singleton)
            .As<IEligibleWorkerQuery>();

        builder.Register<SurvivalBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<ButcherBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>()
            .As<IBuildingWorkCompletionFallbackHandler>();
        builder.Register<ResearchFacilityOperationFallbackHandler>(Lifetime.Singleton)
            .As<IBuildingWorkCompletionFallbackHandler>();
        builder.Register<EquipmentCraftingBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<ModularBuildingCoreFacilityEffectsAdapter>(Lifetime.Singleton)
            .As<DungeonStory.Buildings.IBuildingCoreFacilityEffectsPort>();
        builder.Register<DungeonStory.Buildings.ProductionBuildingAbilityHandler>(Lifetime.Singleton);
        builder.Register<DungeonStory.Buildings.CleaningBuildingAbilityHandler>(Lifetime.Singleton);
        builder.Register<DungeonStory.Buildings.SecurityBuildingAbilityHandler>(Lifetime.Singleton);
        builder.Register<DungeonStory.Buildings.ReceptionBuildingAbilityHandler>(Lifetime.Singleton);
        builder.Register<DungeonStory.Buildings.PatrolPostBuildingAbilityHandler>(Lifetime.Singleton);
        builder.Register<DungeonStory.Buildings.OutdoorRestBuildingAbilityHandler>(Lifetime.Singleton);
        builder.Register<DungeonStory.Buildings.ExteriorMaintenanceBuildingAbilityHandler>(Lifetime.Singleton);
        builder.Register<ProductionBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<CleaningBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<SecurityBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<ReceptionBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<PatrolPostBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<OutdoorRestBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<ExteriorMaintenanceBuildingAbilityHandler>(Lifetime.Singleton)
            .As<IBuildingAbilityWorkCompletedHandler>();
        builder.Register<BuildingAbilityRuntimeDispatcher>(Lifetime.Singleton)
            .As<IBuildingAbilityRuntimeDispatcher>();
    }

    private static void RegisterWorkStatPolicies(IContainerBuilder builder)
    {
        builder.Register<ConstructionRepairStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<CookingButcherStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<ResearchStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<CleaningStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<HaulStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<TreatmentStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<SurgeryStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<GuardHuntStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<GatheringStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<AnimalCareStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<GrandProjectStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<ThreatMitigationStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
        builder.Register<PlumbingStatPolicy>(Lifetime.Singleton)
            .As<IWorkStatPolicy>();
    }
}
