using UnityEngine.SceneManagement;
using VContainer;
using VContainer.Unity;
using DungeonStory.Balance;

public static class DungeonWorldSimulationRegistration
{
    public static void RegisterDungeonWorldSimulation(
        this IContainerBuilder builder,
        Scene scopeScene,
        WorldSimulationSceneReferences sceneReferences)
    {
        builder.RegisterInstance(sceneReferences
            ?? throw new System.ArgumentNullException(nameof(sceneReferences)));
        builder.Register<WorldDropZoneQuery>(Lifetime.Singleton)
            .As<IWorldDropZoneQuery>();
        builder.Register<ExteriorIncidentActorService>(Lifetime.Singleton)
            .As<IExteriorIncidentActorService>();
        builder.Register<MerchantCartExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<InformantExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<ThiefExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<InjuredReturneeExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<PredatorApproachExteriorIncidentHandler>(Lifetime.Singleton)
            .AsSelf()
            .As<IExteriorIncidentHandler>();
        builder.Register<CargoDamageExteriorIncidentHandler>(Lifetime.Singleton)
            .As<IExteriorIncidentHandler>();
        builder.Register<ExteriorIncidentHandlerRegistry>(Lifetime.Singleton);
        builder.Register<ExteriorZoneWorldQuery>(Lifetime.Singleton)
            .As<IExteriorZoneQuery>();
        builder.Register<ExteriorActivityWorldServices>(Lifetime.Singleton);
        builder.Register<ExteriorActivityDomainServices>(Lifetime.Singleton);
        builder.Register<ExteriorActivityExecutionServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<ExteriorActivityRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IExteriorActivityRuntime>()
            .As<IExteriorPatrolRuntime>()
            .As<IExteriorIncidentRuntime>()
            .As<IExpeditionDepartureService>()
            .As<IExpeditionReturnService>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ResourceEconomyContentCatalog>(Lifetime.Singleton)
            .As<IResourceEconomyContentCatalog>();
        builder.Register<SurvivalContinuityCatalogQuery>(Lifetime.Singleton)
            .As<DungeonStory.Balance.ISurvivalContinuityCatalogQuery>();
        builder.RegisterDungeonGameContentCatalog();
        builder.Register<GameContentWasteProcessingRules>(Lifetime.Singleton)
            .As<IWasteProcessingRules>();
        builder.Register<AuthoredGameplayCatalog>(Lifetime.Singleton)
            .As<IMetaUpgradeDefinitionCatalog>()
            .As<IRunVariableDefinitionCatalog>()
            .As<IOwnerDoctrineDefinitionCatalog>()
            .As<IInvasionIntruderPatternDefinitionCatalog>()
            .As<ICharacterNeedDefinitionCatalog>()
            .As<ICharacterNeedDefinitionQuery>()
            .As<IStockCategoryDefinitionCatalog>()
            .As<IBuildingCategoryDefinitionCatalog>();
        builder.Register<RuntimeBuildingArchetypeCatalog>(Lifetime.Singleton)
            .As<IRuntimeBuildingArchetypeCatalog>();
        builder.Register<ResourceItemDefinitionCatalog>(Lifetime.Singleton)
            .As<IItemDefinitionCatalog>();
        builder.Register<ResourceDungeonItemCatalogProvider>(Lifetime.Singleton)
            .As<IDungeonItemCatalogProvider>();
        builder.Register<GenericDefinitionPhysicalItemMassProjector>(
                Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>()
            .As<IPhysicalItemDefinitionMassProjector>();
        builder.Register<CombatEquipmentPhysicalItemMassProjector>(
                Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>();
        builder.Register<ApparelPhysicalItemMassProjector>(Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>();
        builder.Register<WildlifeCarcassPhysicalItemMassProjector>(
                Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>();
        builder.Register<PackagedLotPhysicalItemMassProjector>(Lifetime.Singleton)
            .As<IPhysicalItemMassProjector>();
        builder.Register<PhysicalItemMassQuery>(Lifetime.Singleton)
            .As<IPhysicalItemMassQuery>()
            .As<IPackagedLotDefinitionQuery>();
        builder.Register<PackagedLotTareOutputGateway>(Lifetime.Singleton)
            .As<IPackagedLotTareOutputGateway>();
        builder.Register<PackagedLotTareDispositionService>(Lifetime.Singleton)
            .As<IPackagedLotTareDispositionService>();
        builder.Register<ResourceItemHaulingSettingsProvider>(
                Lifetime.Singleton)
            .As<IItemHaulingSettingsProvider>();
        builder.Register<ItemMarkerPresenter>(Lifetime.Singleton)
            .As<IItemMarkerPresenter>();
        builder.Register<WorldItemRepository>(Lifetime.Singleton)
            .AsSelf()
            .As<IItemInstanceRepository>();
        builder.Register<FacilityBufferDestinationClaimRegistry>(Lifetime.Singleton)
            .AsSelf()
            .As<IFacilityBufferDestinationClaimQuery>()
            .As<IFacilityBufferDestinationClaimAuthorityQuery>()
            .As<IFacilityBufferDestinationClaimCommand>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<FacilityBufferPhysicalOccupancyQuery>(Lifetime.Singleton)
            .As<IFacilityBufferPhysicalOccupancyQuery>();
        builder.Register<FacilityOutputClearanceTelemetryRuntime>(
                Lifetime.Singleton)
            .As<IFacilityOutputClearanceTelemetrySink>()
            .As<IFacilityOutputClearanceTelemetryQuery>()
            .As<IFacilityOutputClearanceTelemetryControl>()
            .As<IDungeonSaveCaptureGuard>()
            .As<IDungeonSaveRestoreCompletedHook>();
        builder.Register<FacilityBufferMassAdmissionService>(Lifetime.Singleton)
            .As<IFacilityBufferMassAdmissionService>()
            .As<IFacilityBufferPlannedOutputProjectionQuery>()
            .As<IFacilityBufferMassCapacityQuery>()
            .As<IFacilityBufferMassCapacityAuthorityQuery>()
            .As<IFacilityBufferMassCapacityCommand>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<FacilityBufferPlannedOutputPublicationService>(
                Lifetime.Singleton)
            .As<IFacilityBufferPlannedOutputPublicationService>();
        builder.Register<FacilityOutputExactRouteService>(Lifetime.Singleton)
            .As<IFacilityOutputExactRoutePort>()
            .As<IFacilityOutputExactRouteOutboxQuery>()
            .As<IFacilityOutputExactRouteDeliveryOverlayParticipant>()
            .As<IFacilityOutputExactRouteOutboxPersistence>()
            .As<IFacilityOutputExactRouteRestoreReconciler>()
            .As<IPreparedOutputCheckpointGcParticipant>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<FacilityBufferDestinationLifecycleService>(Lifetime.Singleton)
            .As<IFacilityBufferDestinationLifecycleCommand>();
        builder.Register<FacilityBufferDestinationReleaseService>(Lifetime.Singleton)
            .As<IFacilityBufferDestinationReleaseService>();
        builder.Register<CharacterCarryInventoryRegistry>(Lifetime.Singleton)
            .As<ICharacterCarryInventoryRegistry>()
            .As<ICharacterSkillTransientStateRegistry>()
            .As<ICharacterRuntimeTransientStateRegistry>();
        builder.Register<PhysicalStockQuery>(Lifetime.Singleton)
            .As<IStockQuery>();
        builder.Register<WarehouseMassAdmissionService>(Lifetime.Singleton)
            .AsSelf()
            .As<IWarehouseMassAdmissionService>()
            .As<IWarehouseMassAdmissionLedgerQuery>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<WarehouseLifecycleOccupancyQuery>(Lifetime.Singleton)
            .As<IWarehouseLifecycleOccupancyQuery>();
        builder.Register<FloorClutterDiagnosticsQuery>(Lifetime.Singleton)
            .As<IFloorClutterDiagnosticsQuery>();
        builder.Register<ItemQuantityReservationService>(Lifetime.Singleton)
            .AsSelf()
            .As<IItemQuantityReservationService>()
            .As<IItemQuantityLeaseMutation>()
            .As<IItemQuantityReservationPersistence>()
            .As<IItemReservationMutationGate>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ApparelLeaseAuthorityPort>(Lifetime.Singleton)
            .As<IApparelLeaseAuthorityQuery>()
            .As<IApparelLeaseAuthorityCommand>();
        builder.Register<ItemReservationService>(Lifetime.Singleton)
            .As<IItemReservationService>();
        builder.Register<LeasedItemReservationService>(Lifetime.Singleton)
            .As<ILeasedItemReservationService>();
        builder.Register<AtomicItemConsumptionService>(Lifetime.Singleton)
            .As<IAtomicItemConsumptionService>();
        builder.Register<WorldItemSpawner>(Lifetime.Singleton)
            .As<IWorldItemSpawner>();
        builder.Register<PhysicalItemTransformService>(Lifetime.Singleton)
            .As<IPhysicalItemTransformService>();
        builder.Register<PhysicalItemRelocationService>(Lifetime.Singleton)
            .As<IPhysicalItemRelocationService>();
        builder.Register<PhysicalItemBatchDispositionService>(Lifetime.Singleton)
            .As<IPhysicalItemBatchDispositionService>()
            .As<IReservedPhysicalItemBatchDispositionService>()
            .As<ICarriedPhysicalItemBatchDispositionService>();
        builder.Register<ProductionPhysicalCustodyDrainOutbox>(Lifetime.Singleton)
            .As<IProductionPhysicalCustodyDrainOutbox>();
        builder.Register<ProductionInputDestinationCustodyDrainOutbox>(Lifetime.Singleton)
            .As<IProductionInputDestinationCustodyDrainOutbox>();
        builder.Register<ProductionInputDestinationCustodyDrainService>(Lifetime.Singleton)
            .As<IProductionInputDestinationCustodyDrainService>();
        builder.Register<FacilityBufferDestinationCustodyDrainService>(
                Lifetime.Singleton)
            .As<IFacilityBufferDestinationCustodyDrainService>()
            .As<IFacilityBufferDestinationCustodyDrainRestoreCandidateQuery>()
            .As<IFacilityBufferDestinationCustodyDrainCheckpointGcPort>()
            .As<IFacilityBufferDestinationCustodyDrainLiveQuery>();
        builder.Register<ProductionCapacityRoutingDrainOutbox>(Lifetime.Singleton)
            .As<IProductionCapacityRoutingDrainOutbox>()
            .As<IProductionCapacityRoutingDrainQuery>();
        builder.Register<PhysicalFacilityItemSinkGateway>(Lifetime.Singleton)
            .As<IPhysicalFacilityItemSinkGateway>()
            .As<IPhysicalFacilityItemBatchSinkGateway>()
            .As<IPhysicalFacilityItemBatchTransferGateway>();
        builder.Register<PhysicalItemSourcePublicationService>(Lifetime.Singleton)
            .As<IPhysicalItemSourcePublicationService>();
        builder.Register<PhysicalItemExactSourcePublicationService>(
                Lifetime.Singleton)
            .As<IPhysicalItemExactSourcePublicationService>()
            .As<IPhysicalItemExactSourceRestoreAuthorityCommand>()
            .As<IDungeonSaveCaptureGuard>();
        builder.Register<WorldItemQueryService>(Lifetime.Singleton)
            .AsSelf()
            .As<IWorldItemQueryService>();
        builder.Register<ProductionCapacityRoutingPhysicalSourceQuery>(
                Lifetime.Singleton)
            .As<IProductionCapacityRoutingPhysicalSourceQuery>();
        builder.Register<ProductionCapacityRoutingHaulPlanFence>(
                Lifetime.Singleton)
            .As<IProductionCapacityRoutingHaulPlanFence>();
        builder.Register<WorldItemHaulPlanningService>(Lifetime.Singleton)
            .As<IWorldItemHaulPlanningService>()
            .As<IWorldItemDeliveryReachabilityQuery>();
        builder.Register<ItemTransferService>(Lifetime.Singleton)
            .As<IItemTransferService>()
            .As<IReservedItemTransferService>()
            .As<IProductionCapacityRoutingActorQuiescence>();
        builder.Register<
                ProductionCapacityRoutingOperationAuthorityReleaseCoordinator>(
                Lifetime.Singleton)
            .As<IProductionCapacityRoutingOperationAuthorityReleaseCoordinator>();
        builder.RegisterEntryPoint<BufferStackAggregationService>(Lifetime.Singleton)
            .As<IBufferStackAggregationService>();
        builder.Register<WorldItemPersistenceService>(Lifetime.Singleton);
        builder.Register<WorldItemWarehouseService>(Lifetime.Singleton);
        // Shared admission participant for the live prepared-output delivery
        // coordinator and warehouse haul-planner authority validation.
        builder.Register<PreparedOutputExactDestinationAdmissionParticipant>(
                Lifetime.Singleton)
            .As<IPreparedOutputExactDestinationAdmissionParticipant>();
        builder.Register<WorldItemTheftService>(Lifetime.Singleton);
        builder.Register<WorldItemReadServices>(Lifetime.Singleton);
        builder.Register<WorldItemMutationServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WorldItemStackRuntime>(Lifetime.Singleton)
            .As<IWorldItemStackRuntime>()
            .As<IPhysicalItemRestoreStaging>()
            .As<IPhysicalItemRestoreCandidateQuery>()
            .As<IProductionInputDestinationCustodyDrainRestoreCandidateQuery>()
            .As<IPhysicalItemRestoreCandidateOutputQuery>()
            .As<IFacilityBufferPlannedOutputRestoreCandidateQuery>()
            .As<IFacilityBufferAcknowledgedOutputRestoreCandidateQuery>()
            .As<IFacilityOutputExactRouteRestoreCandidateQuery>()
            .As<IWarehouseOverCapacityEvacuationQuery>()
            .As<IEquipmentPhysicalItemGateway>()
            .As<IHaulDeliveryIntentCommand>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<BuildingItemStackPortAdapter>(Lifetime.Singleton)
            .As<IBuildingItemStackPort>();
        builder.Register<ResourceUsageIndex>(Lifetime.Singleton)
            .As<IResourceUsageIndex>()
            .As<IProductionDependencyCatalog>();
        builder.Register<ProductionItemGateway>(Lifetime.Singleton)
            .As<IProductionItemGateway>()
            .As<IProductionOutputBufferGateway>();
        builder.Register<ProductionStockSensorPhysicalGateway>(Lifetime.Singleton)
            .As<IProductionStockSensorPhysicalGateway>();
        builder.Register<ProductionStockSensorRemovalOutputGateway>(Lifetime.Singleton)
            .As<IProductionStockSensorRemovalOutputGateway>();
        builder.Register<ProductionWorkshopRuntime>(Lifetime.Singleton)
            .As<IProductionWorkshopRuntime>();
        builder.Register<ServiceRoomLinkRuntime>(Lifetime.Singleton)
            .As<IServiceRoomLinkRuntime>();
        builder.Register<ResourceServiceProcessCatalog>(Lifetime.Singleton)
            .As<IServiceProcessCatalog>();
        builder.Register<BlueprintServiceRoomResearchQuery>(Lifetime.Singleton)
            .As<IServiceRoomResearchQuery>();
        builder.Register<ServiceSessionRuntime.Dependencies>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<ServiceSessionRuntime>(Lifetime.Singleton)
            .As<IServiceSessionRuntime>()
            .As<ISurvivalServiceSessionCapability>()
            .As<IServiceAvailabilityQuery>()
            .As<IServiceDemandPolicyRuntime>();
        builder.Register<ProductionOutputPlanningService>(Lifetime.Singleton)
            .As<IProductionOutputPlanningService>();
        builder.Register<CanonicalProductionOutputResolver>(Lifetime.Singleton);
        builder.Register<ProductionPreparedOutputComponentCodec>(Lifetime.Singleton)
            .As<IProductionPreparedOutputComponentCodec>()
            .As<IProductionPreparedOutputMaterializer>();
        builder.Register<CombatAmmunitionPreparedOutputMaterializer>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputMaterializer>();
        builder.Register<PerishableFoodPreparedOutputMaterializer>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputMaterializer>();
        builder.Register<StandardDefinitionProductionOutputCapability>(
                Lifetime.Singleton)
            .As<IProductionOutputCapability>()
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<ApparelWorkOrderOutputCapability>(Lifetime.Singleton)
            .As<IProductionOutputCapability>()
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<CombatEquipmentCraftOutputCapability>(Lifetime.Singleton)
            .As<IProductionOutputCapability>()
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<CombatAmmunitionCraftOutputCapability>(Lifetime.Singleton)
            .As<IProductionOutputCapability>()
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<PerishableFoodOutputCapability>(Lifetime.Singleton)
            .As<IProductionOutputCapability>()
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<CertifiedSeedOutputCapability>(Lifetime.Singleton)
            .As<IProductionOutputCapability>()
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<CropHarvestSeedLotOutputCapability>(Lifetime.Singleton)
            .As<IProductionOutputCapability>()
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<EnvironmentalWorkwearProductionOutputMaximumMassCapability>(
                Lifetime.Singleton)
            .As<IProductionOutputMaximumMassCapability>();
        builder.Register<ProductionOutputHandlerRegistry>(Lifetime.Singleton)
            .AsSelf()
            .As<IProductionOutputCapabilityRegistry>();
        builder.Register<ProductionPreparedOutputMaterializerRegistry>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IProductionPreparedOutputMaterializerRegistry>();
        builder.Register<ProductionOutputMaximumMassRegistry>(Lifetime.Singleton)
            .AsSelf()
            .As<IProductionOutputMaximumMassRegistry>()
            .As<IProductionOutputMaximumMassCapabilitySelector>();
        builder.Register<ProductionFacilityOutputCapacityBranchMassAuthority>(
                Lifetime.Singleton)
            .As<IProductionFacilityOutputCapacityBranchMassQuery>();
        builder.Register<GameplayEffectResultBoundsCatalog>(Lifetime.Singleton)
            .As<IGameplayEffectResultBoundsQuery>();
        builder.Register<CertifiedSeedFacilityOutputCapacityContributor>(
                Lifetime.Singleton)
            .As<IProductionFacilityOutputCapacityContributor>();
        builder.Register<ApparelFacilityOutputCapacityContributor>(
                Lifetime.Singleton)
            .As<IProductionFacilityOutputCapacityContributor>();
        builder.Register<CombatCraftFacilityOutputCapacityContributor>(
                Lifetime.Singleton)
            .As<IProductionFacilityOutputCapacityContributor>();
        builder.Register<
                NaturalGoldenHarvestReachableMaximumWitnessContributor>(
                Lifetime.Singleton)
            .As<ICropHarvestReachableMaximumWitnessContributor>();
        builder.Register<CropHarvestFacilityOutputCapacityContributor>(
                Lifetime.Singleton)
            .As<IProductionFacilityOutputCapacityContributor>();
        builder.Register<ProductionFacilityOutputCapacityContributorRegistry>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IProductionFacilityOutputCapacityContributorRegistry>();
        builder.Register<CertifiedSeedCycleMaximumAuthority>(Lifetime.Singleton)
            .As<ICertifiedSeedCycleMaximumQuery>();
        builder.Register<CertifiedSeedSpecialThroughputContributor>(
                Lifetime.Singleton)
            .As<IProductionSpecialThroughputContributor>();
        builder.Register<CropHarvestCycleMaximumAuthority>(Lifetime.Singleton)
            .As<ICropHarvestCycleMaximumQuery>();
        builder.Register<CropHarvestSpecialThroughputContributor>(
                Lifetime.Singleton)
            .As<IProductionSpecialThroughputContributor>();
        builder.Register<ApparelCraftCycleMaximumAuthority>(Lifetime.Singleton)
            .As<IApparelCraftCycleMaximumQuery>();
        builder.Register<ApparelSpecialThroughputContributor>(
                Lifetime.Singleton)
            .As<IProductionSpecialThroughputContributor>();
        builder.Register<CombatCraftCycleMaximumAuthority>(Lifetime.Singleton)
            .As<ICombatCraftCycleMaximumQuery>();
        builder.Register<CombatCraftSpecialThroughputContributor>(
                Lifetime.Singleton)
            .As<IProductionSpecialThroughputContributor>();
        builder.Register<ProductionSpecialThroughputContributorRegistry>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<
                ProductionResolvedOutputRestoreCapabilityValidatorRegistry>(
                Lifetime.Singleton)
            .As<IProductionResolvedOutputRestoreCapabilityValidatorRegistry>();
        builder.Register<ProductionDomainOutputPublicationService>(
                Lifetime.Singleton)
            .As<IProductionDomainOutputPublicationService>();
        builder.Register<ProductionDomainOutputRestoreJoin>(Lifetime.Singleton)
            .As<IProductionDomainOutputRestoreJoin>();
        builder.Register<ProductionMaximumOutputFactorCatalog>(Lifetime.Singleton)
            .As<IProductionMaximumOutputFactorCatalog>();
        builder.Register<ProductionPassiveBatchOutputPortfolioAuthority>(
                Lifetime.Singleton)
            .As<IProductionPassiveBatchOutputPortfolioQuery>();
        builder.Register<ProductionRecipeThroughputBranchAuthority>(
                Lifetime.Singleton)
            .As<IProductionRecipeThroughputBranchQuery>();
        builder.Register<ProductionFacilityDefinitionCatalog>(Lifetime.Singleton);
        builder.Register<BuildingCraftsmanshipDefinitionMaximumQuery>(
                Lifetime.Singleton)
            .As<IBuildingCraftsmanshipDefinitionMaximumQuery>();
        builder.Register<ProductionAutomationAssistedWorkDefinitionMaximumQuery>(
                Lifetime.Singleton)
            .As<IAutomationAssistedWorkDefinitionMaximumQuery>();
        builder.Register<ProductionAutomaticWorkRateMaximumQuery>(
                Lifetime.Singleton)
            .As<IProductionAutomaticWorkRateMaximumQuery>();
        builder.Register<ProductionWorkStatPolicyMaximumContributor>(
                Lifetime.Singleton)
            .As<IProductionRecipeWorkRateMaximumContributor>();
        builder.Register<ProductionCharacterPerformanceMaximumContributor>(
                Lifetime.Singleton)
            .As<IProductionRecipeWorkRateMaximumContributor>();
        builder.Register<ProductionCharacterWorkContextMaximumContributor>(
                Lifetime.Singleton)
            .As<IProductionRecipeWorkRateMaximumContributor>();
        builder.Register<ProductionWorkEnvironmentMaximumContributor>(
                Lifetime.Singleton)
            .As<IProductionRecipeWorkRateMaximumContributor>();
        builder.Register<ProductionCraftsmanshipMaximumContributor>(
                Lifetime.Singleton)
            .As<IProductionRecipeWorkRateMaximumContributor>();
        builder.Register<ProductionFacilityEvolutionWorkRateMaximumContributor>(
                Lifetime.Singleton)
            .As<IProductionRecipeWorkRateMaximumContributor>();
        builder.Register<ProductionAutomationAssistedWorkMaximumContributor>(
                Lifetime.Singleton)
            .As<IProductionRecipeWorkRateMaximumContributor>();
        builder.RegisterInstance(
            ProductionWorkRateContributorManifest.CreateCanonical());
        builder.Register<ProductionRecipeWorkRateMaximumAuthority>(
                Lifetime.Singleton)
            .As<IProductionRecipeWorkRateMaximumQuery>()
            .As<IProductionWorkRateMaximumQuery>();
        builder.Register<ProductionOutputDestinationAuthorityRuntime>(
                Lifetime.Singleton)
            .As<IProductionOutputDestinationAuthorityRuntime>();
        builder.Register<ProductionStockSensorDestinationAuthorityRuntime>(
                Lifetime.Singleton)
            .As<IProductionStockSensorDestinationAuthorityRuntime>();
        builder.Register<ProductionFacilityMutationEpochRuntime>(Lifetime.Singleton)
            .AsSelf();
        builder.Register<ProductionActiveFacilityRetargetStateStore>(
                Lifetime.Singleton)
            .As<IProductionActiveFacilityRetargetStateStore>();
        builder.Register<ProductionActiveMultiFacilityRetargetAdapter>(
                Lifetime.Singleton)
            .As<IProductionFacilityRetargetAuthorityAdapter>();
        builder.Register<ProductionPreparedRoutingIdentityRetargetAdapter>(
                Lifetime.Singleton)
            .As<IProductionFacilityRetargetAuthorityAdapter>();
        builder.Register<ProductionFacilityRetargetAuthorityParticipant>(
                Lifetime.Singleton)
            .As<IProductionFacilityRetargetParticipant>();
        builder.Register<ProductionFacilityEmptyLifecycleRetargetParticipant>(
                Lifetime.Singleton)
            .As<IProductionFacilityRetargetParticipant>();
        builder.Register<ProductionFacilityRetargetParticipantRegistry>(
            Lifetime.Singleton);
        builder.Register<ProductionFacilityRetargetTransaction>(Lifetime.Singleton)
            .As<IProductionFacilityRetargetTransaction>();
        builder.Register<ProductionFacilityDestructiveDrainOpenOperationQuery>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainOpenOperationQuery>();
        builder.Register<ProductionFacilityMutationAdmissionFenceSource>(
                Lifetime.Singleton)
            .As<IFacilityBufferDestinationAdmissionFenceSource>();
        builder.Register<DurableFacilityEquipmentAdmissionFenceRegistry>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentAdmissionFenceCommand>()
            .As<IFacilityBufferDestinationAdmissionFenceSource>();
        builder.Register<FacilityBufferDestinationAdmissionFenceQuery>(
                Lifetime.Singleton)
            .As<IFacilityBufferDestinationAdmissionFenceQuery>();
        builder.Register<ResearchArcaneIndexEquipmentPolicySource>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicySource>()
            .As<IResearchDurableEquipmentWorkPolicySource>();
        builder.Register<CareerDurableEquipmentPolicySource>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicySource>();
        builder.Register<ReproductionDurableEquipmentPolicySource>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicySource>();
        builder.Register<ClimateDurableEquipmentPolicySource>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicySource>();
        builder.Register<RunAdministrativeSealDurableEquipmentPolicySource>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicySource>();
        builder.Register<InvasionSignalHornDurableEquipmentPolicySource>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicySource>();
        builder.Register<InvasionDefenseKitSupplyPolicySource>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicySource>();
        builder.Register<CircusPerformanceSupplyPolicySource>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicySource>();
        builder.Register<ResearchDurableEquipmentWorkPolicyRegistry>(
                Lifetime.Singleton)
            .As<IResearchDurableEquipmentWorkPolicyQuery>();
        builder.RegisterEntryPoint<ResearchDurableEquipmentLifecycleRuntime>(
                Lifetime.Singleton)
            .As<IDungeonSaveCaptureGuard>();
        builder.RegisterEntryPoint<ClimateDurableEquipmentLifecycleRuntime>(
                Lifetime.Singleton)
            .As<IDungeonSaveCaptureGuard>();
        builder.RegisterEntryPoint<RunInvasionDurableEquipmentLifecycleRuntime>(
                Lifetime.Singleton)
            .As<IDungeonSaveCaptureGuard>();
        builder.RegisterEntryPoint<InvasionDefenseKitSupplyLifecycleRuntime>(
                Lifetime.Singleton)
            .As<IDungeonSaveCaptureGuard>();
        builder.RegisterEntryPoint<CircusPerformanceSupplyLifecycleRuntime>(
                Lifetime.Singleton)
            .As<IDungeonSaveCaptureGuard>();
        builder.Register<DurableFacilityEquipmentPolicyRegistry>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPolicyQuery>();
        builder.Register<DefinitionMassDurableFacilityEquipmentCapacityProjector>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentCapacityProjector>();
        builder.Register<DurableFacilityEquipmentCapacityProjectionRegistry>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentCapacityProjectionQuery>();
        builder.Register<PositiveDurabilityComponentUsabilityPolicy>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentUsabilityPolicy>();
        builder.Register<CircusPerformanceSupplyUsabilityPolicy>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentUsabilityPolicy>();
        builder.Register<InvasionDefenseKitSupplyUsabilityPolicy>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentUsabilityPolicy>();
        builder.Register<DurableFacilityEquipmentUsabilityRegistry>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentUsabilityQuery>();
        builder.Register<PositiveDurabilityComponentWearPolicy>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentWearPolicy>();
        builder.Register<CircusPerformanceSupplyWearPolicy>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentWearPolicy>();
        builder.Register<DurableFacilityEquipmentWearRegistry>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentWearQuery>();
        builder.Register<DurableFacilityEquipmentPhysicalPort>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentPhysicalPort>()
            .As<IDurableFacilityEquipmentComponentMutationPort>();
        builder.Register<DurableFacilityEquipmentSlotRuntime>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentSlotCommand>()
            .As<IDurableFacilityEquipmentSlotQuery>()
            .As<IDurableFacilityEquipmentSlotPersistence>()
            .As<IDurableFacilityEquipmentSlotCheckpointGcPort>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<DurableFacilityEquipmentUseRuntime>(
                Lifetime.Singleton)
            .As<IDurableFacilityEquipmentUseCommand>();
        builder.Register<RunAdministrativeSealDurableEquipmentRuntime>(
            Lifetime.Singleton);
        builder.Register<InvasionSignalHornDurableEquipmentRuntime>(
            Lifetime.Singleton);
        builder.Register<InvasionDefenseKitSupplyRuntime>(
            Lifetime.Singleton);
        builder.Register<DurableFacilityEquipmentRestoreProjection>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<DurableFacilityEquipmentSlotRecoveryRuntime>(
                Lifetime.Singleton)
            .As<IDungeonSaveRestoreCompletedHook>()
            .As<IDungeonSaveCaptureGuard>();
        builder.Register<ProductionFacilityMutationAuthorityGate>(
                Lifetime.Singleton)
            .As<IProductionFacilityMutationEpochQuery>()
            .As<IProductionFacilityMutationEpochAuthority>();
        builder.RegisterFactory<IProductionAssemblyBridge>(
            resolver => () => resolver.Resolve<IProductionAssemblyBridge>(),
            Lifetime.Singleton);
        builder.RegisterFactory<IProductionOutputMaximumMassRegistry>(
            resolver => () => resolver.Resolve<
                IProductionOutputMaximumMassRegistry>(),
            Lifetime.Singleton);
        builder.RegisterFactory<IProductionFacilityOutputCapacityContributorRegistry>(
            resolver => () => resolver.Resolve<
                IProductionFacilityOutputCapacityContributorRegistry>(),
            Lifetime.Singleton);
#if UNITY_EDITOR
        if (ProductionOutputClearanceNaturalBootstrapProfileSource.IsRequested)
        {
            builder.Register<ProductionOutputClearanceNaturalBootstrapProfileSource>(
                    Lifetime.Singleton)
                .As<IProductionOutputClearanceProfileSource>();
        }
        else
#endif
        {
            builder.Register<ProductionOutputClearanceProfileResourceSource>(
                    Lifetime.Singleton)
                .As<IProductionOutputClearanceProfileSource>();
        }
        builder.Register<ProductionOutputBufferCapacityProjector>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IProductionOutputBufferCapacityProjector>();
        builder.Register<ProductionOutputDetachedFacilityCapacityRestoreGuard>(
                Lifetime.Singleton)
            .As<IProductionOutputDetachedFacilityCapacityRestoreGuard>()
            .As<IProductionOutputDetachedFacilityCapacityProjectionQuery>();
        builder.Register<ProductionPreparedOutputRoutingAuthority>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputRoutingAuthority>()
            .As<IProductionPreparedOutputRoutingBatchQuery>()
            .As<IProductionPreparedOutputDeliveryRerouteParticipant>()
            .As<IProductionPreparedOutputRoutingPersistence>()
            .As<IProductionPreparedOutputRoutingRestoreReconciler>()
            .As<IPreparedOutputCheckpointGcParticipant>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ProductionPreparedOutputDeliveryCoordinator>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputDeliveryCoordinator>();
        builder.Register<ProductionPreparedOutputExactRouteLifecycle>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputExactRouteLifecycle>();
        builder.Register<ProductionCapacityRoutingDrainExecutionCoordinator>(
                Lifetime.Singleton)
            .As<IProductionCapacityRoutingDrainExecutionCoordinator>();
        builder.Register<ProductionPreparedOutputRoutingRestoreJoin>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputRoutingRestoreJoin>();
        builder.RegisterInstance(
            ProductionMassExplanationCapabilityRegistry.CreateDefault());
        builder.Register<ProductionPreparedOutputExecutionAdapter>(
                Lifetime.Singleton)
            .As<IProductionPreparedOutputExecutionPort>()
            .As<IProductionRuinedBatchExecutionPort>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ProductionRecipeExecutionReceiptAuthority>(
                Lifetime.Singleton)
            .As<IProductionRecipeExecutionReceiptAuthority>()
            .As<IProductionRecipeExecutionCorrelationCommand>()
            .As<IProductionRecipeExecutionReceiptQuery>();
        builder.Register<ProductionPreparedOutputRestoreJoin>(Lifetime.Singleton)
            .As<IProductionPreparedOutputRestoreJoin>();
        builder.Register<ProductionExactCapabilityOutputRestoreJoin>(
                Lifetime.Singleton)
            .As<IProductionExactCapabilityOutputRestoreJoin>();
        builder.Register<ProductionFacilityDestructiveDrainStartPreflight>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainStartPreflight>();
        builder.Register<ProductionCycleUtilityService>(Lifetime.Singleton)
            .As<IProductionCycleUtilityService>();
        builder.Register<ProductionInputLogisticsService>(Lifetime.Singleton)
            .As<IProductionInputLogisticsService>();
        builder.Register<ProductionFacilityHandleQueryAdapter>(Lifetime.Singleton)
            .As<IProductionFacilityHandleQuery>();
        builder.Register<ProductionAssemblyBridgeAdapter>(Lifetime.Singleton)
            .As<IProductionAssemblyBridge>();
        builder.Register<ProductionInputDestinationClaimRuntime>(Lifetime.Singleton)
            .As<IProductionInputDestinationClaimRuntime>();
        builder.Register<ProductionGenericBillTerminalDrainOutbox>(Lifetime.Singleton)
            .As<IProductionGenericBillTerminalDrainQuery>()
            .As<IProductionGenericBillTerminalDrainCommand>();
        builder.Register<ProductionAggregateStateStore>(Lifetime.Singleton);
        builder.Register<ProductionRecipeConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.Register<ProductionConstructionConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.Register<ProductionEquipmentConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.Register<ProductionSurgeryConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.Register<ResourceStockPolicyQuery>(Lifetime.Singleton)
            .As<IResourceStockPolicyQuery>();
        builder.Register<ProductionMarketSaleConsumerDemandProvider>(
                Lifetime.Singleton)
            .As<IProductionConsumerDemandProvider>();
        builder.RegisterEntryPoint<ProductionDistributionRuntime>(
                Lifetime.Singleton)
            .As<IProductionDistributionQuery>();
        builder.Register<ProductionBillOrderDependencies>(Lifetime.Singleton);
        builder.Register<ProductionBillExecutionDependencies>(Lifetime.Singleton);
        builder.Register<ProductionOutputExecutionService>(Lifetime.Singleton)
            .As<IProductionOutputExecutionService>();
        builder.Register<ProductionStockSensorRuntime>(Lifetime.Singleton)
            .As<IProductionStockSensorRuntime>()
            .As<IProductionStockSensorDestructiveDrainPort>();
        builder.Register<ProductionBillSnapshotProjector>(Lifetime.Singleton)
            .As<IProductionBillSnapshotProjector>();
        builder.RegisterEntryPoint<ProductionBillRuntime>(Lifetime.Singleton)
            .As<IProductionBillCoreQuery>()
            .As<IProductionFacilityDestructiveDrainPreparedOutputQuery>()
            .As<IProductionBillCoreOrderCommand>()
            .As<IProductionBillCoreWorkExecution>()
            .As<IProductionBillDetachedFacilityPersistence>()
            .As<IProductionBillPersistence>();
        builder.Register<ProductionBillLifecycleContributor>(Lifetime.Singleton);
        builder.Register<CombatEquipmentCraftLifecycleContributor>(Lifetime.Singleton);
        builder.Register<ApparelWorkOrderLifecycleContributor>(Lifetime.Singleton);
        builder.Register<ProductionOutputCapacityRoutingLifecycleContributor>(
            Lifetime.Singleton);
        builder.Register<ProductionOutputPhysicalLifecycleContributor>(
            Lifetime.Singleton);
        builder.Register<ProductionStockSensorLifecycleContributor>(
            Lifetime.Singleton);
        builder.Register<ProductionOutputDestinationLifecycleQuery>(Lifetime.Singleton)
            .As<IProductionOutputDestinationLifecycleQuery>();
        builder.Register<ProductionPhysicalCustodyDrainService>(
                Lifetime.Singleton)
            .As<IProductionPhysicalCustodyDrainPort>();
        builder.Register<ProductionApparelOrderTerminalDrainOutbox>(
                Lifetime.Singleton)
            .As<IProductionApparelOrderTerminalDrainQuery>()
            .As<IProductionApparelOrderTerminalDrainCommand>();
        builder.Register<CombatEquipmentCraftTerminalAuthority>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<CombatEquipmentRepairTerminalAuthority>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<CombatEquipmentTerminalSourceAuthorityRouter>(
                Lifetime.Singleton)
            .As<ICombatEquipmentTerminalSourceAuthority>();
        builder.Register<CombatEquipmentTerminalDrainOutbox>(Lifetime.Singleton)
            .As<ICombatEquipmentTerminalDrainQuery>()
            .As<ICombatEquipmentTerminalDrainCommand>();
        builder.Register<CombatEquipmentTerminalDrainSourceAdapter>(
                Lifetime.Singleton)
            .As<ICombatEquipmentTerminalFacilitySourceQuery>();
        builder.Register<CombatEquipmentTerminalFacilityAdapter>(
                Lifetime.Singleton)
            .As<ICombatEquipmentTerminalFacilityQuery>();
        builder.Register<ProductionApparelOrderTerminalDestructiveDrainParticipant>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainParticipant>()
            .As<IProductionFacilityDestructiveDrainCheckpointGcParticipant>();
        builder.Register<CombatEquipmentTerminalDestructiveDrainParticipant>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainParticipant>()
            .As<IProductionFacilityDestructiveDrainCheckpointGcParticipant>();
        builder.Register<ProductionGenericBillTerminalDestructiveDrainParticipant>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainParticipant>()
            .As<IProductionFacilityDestructiveDrainCheckpointGcParticipant>();
        builder.Register<ProductionCapacityRoutingDestructiveDrainParticipant>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainParticipant>()
            .As<IProductionFacilityDestructiveDrainCheckpointGcParticipant>();
        builder.Register<ProductionPhysicalCustodyDestructiveDrainParticipant>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainParticipant>()
            .As<IProductionFacilityDestructiveDrainCheckpointGcParticipant>();
        builder.Register<ProductionStockSensorDestructiveDrainParticipant>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainParticipant>()
            .As<IProductionFacilityDestructiveDrainCheckpointGcParticipant>();
        builder.Register<ProductionFacilityDestructiveDrainParticipantRegistry>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IProductionFacilityDestructiveDrainParticipantRegistry>();
        builder.Register<ProductionFacilityDestructiveDrainJournal>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainJournalQuery>()
            .As<IProductionFacilityDestructiveDrainJournalCommand>()
            .As<IProductionFacilityDestructiveDrainPersistence>()
            .As<IProductionFacilityDestructiveDrainCheckpointGcJournal>();
        builder.Register<ProductionFacilityDestructiveDrainAuthorityStateQuery>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainAuthorityStateQuery>();
        builder.Register<ProductionFacilityDestructiveDrainCoordinator>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainCoordinator>();
        builder.Register<ProductionFacilityDestructiveDrainAuthorityRevoker>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainAuthorityRevoker>();
        builder.Register<ProductionFacilityDestructiveDrainWorldRemovalPort>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainWorldRemovalPort>();
        builder.RegisterEntryPoint<
                ProductionFacilityDestructiveDrainRecoveryRuntime>(
                Lifetime.Singleton)
            .As<IProductionFacilityDestructiveDrainRecoveryRuntime>()
            .As<IDungeonSaveRestoreCompletedHook>()
            .As<IDungeonSaveCaptureGuard>();
        builder.Register<ProductionFacilityMutationFence>(Lifetime.Singleton)
            .As<IProductionFacilityMutationFence>();
        builder.Register<ProductionBillSceneFacade>(Lifetime.Singleton)
            .As<IProductionBillQuery>()
            .As<IProductionBillOrderCommand>()
            .As<IProductionBillWorkExecution>();
        builder.Register<EconomyProjectInputOwnerRuntime>(Lifetime.Singleton)
            .As<IEconomyProjectInputOwnerPort>()
            .As<IEconomyProjectInputOwnerRestoreRuntime>();
        builder.Register<GrandProjectApplicationAdapter>(Lifetime.Singleton)
            .As<IGrandProjectWorldPort>()
            .As<IGrandProjectOperationsPort>();
        builder.RegisterEntryPoint<GrandProjectRuntime>(Lifetime.Singleton)
            .As<IGrandProjectRuntime>()
            .As<IGrandProjectBenefitQuery>();
        builder.Register<ResourceStockPolicyLogisticsDependencies>(Lifetime.Singleton);
        builder.Register<ResourceStockPolicyProductionDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<QualityRejectedSaleDestinationAuthority>(
                Lifetime.Singleton)
            .As<IQualityRejectedSaleDestinationAuthority>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<ResourceStockPolicyRuntime>(
                Lifetime.Singleton)
            .As<IResourceStockPolicyRuntime>();
        builder.Register<RegionalSupplyContractLogisticsDependencies>(Lifetime.Singleton);
        builder.Register<RegionalSupplyContractSessionDependencies>(Lifetime.Singleton);
        builder.Register<RegionalSupplyContractApplicationAdapter>(Lifetime.Singleton)
            .As<IRegionalSupplyContractWorldQuery>()
            .As<IRegionalSupplyContractCommandPort>()
            .As<IRegionalSupplyContractSessionPort>();
        builder.RegisterEntryPoint<RegionalSupplyContractRuntime>(
                Lifetime.Singleton)
            .As<IRegionalSupplyContractRuntime>();
        builder.Register<ResourceEconomyForecastInventoryDependencies>(Lifetime.Singleton);
        builder.Register<ResourceEconomyForecastPopulationDependencies>(Lifetime.Singleton);
        builder.Register<ResourceEconomyForecastPlanningDependencies>(Lifetime.Singleton);
        builder.Register<ResourceEconomyForecastService>(Lifetime.Singleton)
            .As<IResourceEconomyForecastService>();
        builder.Register<WasteProcessingInventoryPortAdapter>(Lifetime.Singleton)
            .As<IWasteProcessingInventoryPort>();
        builder.Register<WasteProcessingProductionPortAdapter>(Lifetime.Singleton)
            .As<IWasteProcessingProductionPort>();
        builder.Register<WasteProcessingMaterialDependencies>(Lifetime.Singleton);
        builder.Register<WasteProcessingOperationDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WasteProcessingRuntime>(Lifetime.Singleton)
            .As<IWasteProcessingQuery>()
            .As<IWastePolicyCommand>()
            .As<IWasteFeedCommand>()
            .As<IWasteFeedCandidateQuery>()
            .As<IWasteProcessingPersistence>();
        builder.Register<WorldFilthSpatialDependencies>(Lifetime.Singleton);
        builder.Register<WorldFilthGameplayDependencies>(Lifetime.Singleton);
        builder.Register<WorldFilthRuntimeDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WorldFilthRuntime>(Lifetime.Singleton)
            .As<IWorldFilthQuery>();
        builder.RegisterEntryPoint<WorldWaterRuntime>(Lifetime.Singleton)
            .As<IWorldWaterQuery>()
            .As<IWorldWaterContaminationCommand>();
        builder.Register<IndustrialInfrastructureTopologyRuntime>(
                Lifetime.Singleton)
            .As<IIndustrialInfrastructureTopologyRuntime>();
        builder.Register<AutomationPowerDemandRegistry>(Lifetime.Singleton)
            .As<IAutomationExecutionModeQuery>()
            .AsSelf();
        builder.RegisterEntryPoint<ElectricalNetworkRuntime>(
                Lifetime.Singleton)
            .As<IPowerInfrastructureQuery>()
            .As<IPowerInfrastructureCommand>()
            .As<IPowerInfrastructurePersistence>();
        builder.RegisterEntryPoint<FluidNetworkRuntime>(Lifetime.Singleton)
            .As<IFluidInfrastructureQuery>()
            .As<IFluidInfrastructureCommand>()
            .As<IFluidInfrastructureTransaction>()
            .As<IManualWaterTransferTransaction>()
            .As<IFluidInfrastructureBatchTransaction>()
            .As<IFluidWastewaterTransaction>()
            .As<IFluidInfrastructurePersistence>();
        builder.Register<WaterFixtureUseRuntime>(Lifetime.Singleton)
            .As<IWaterFixtureUseRuntime>();
        builder.Register<ProcessFluidUseRuntime>(Lifetime.Singleton)
            .As<IProcessFluidUseRuntime>();
        builder.Register<ConveyorItemGateway>(Lifetime.Singleton);
        builder.RegisterEntryPoint<ConveyorRuntime>(Lifetime.Singleton)
            .As<IConveyorInfrastructureQuery>()
            .As<IConveyorInfrastructureCommand>()
            .As<IConveyorPayloadTransaction>()
            .As<IConveyorRestoreProjection>()
            .As<IConveyorRoutingService>();
        builder.Register<ConveyorPersistenceAdapter>(Lifetime.Singleton)
            .As<IConveyorInfrastructurePersistence>();
        builder.RegisterEntryPoint<AutomationRuntime>(Lifetime.Singleton)
            .As<IAutomationInfrastructureQuery>()
            .As<IAutomationInfrastructureCommand>()
            .As<IAutomationInfrastructurePersistence>();
        builder.Register<
                DungeonStory.Environment.EnvironmentalFieldAggregateStateStore>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<EnvironmentalFieldRuntimeApplicationAdapter>(
                Lifetime.Singleton)
            .As<IEnvironmentalFieldQuery>()
            .As<IEnvironmentalFieldCommand>()
            .As<IEnvironmentalFieldPersistence>();
        builder.Register<ResourceEnvironmentalWorkwearCatalog>(
                Lifetime.Singleton)
            .As<IEnvironmentalWorkwearCatalog>();
        builder.Register<ResourceApparelDefinitionCatalog>(Lifetime.Singleton)
            .As<IApparelDefinitionCatalog>();
        builder.Register<ResourceTextileMaterialCatalog>(Lifetime.Singleton)
            .As<ITextileMaterialCatalog>();
        builder.Register<ResourceMaterialEconomicProfileCatalog>(Lifetime.Singleton)
            .As<IMaterialEconomicProfileCatalog>();
        builder.Register<V27BalanceWorkCalculator>(Lifetime.Singleton)
            .As<IBalanceWorkCalculator>()
            .As<IRecipeBalanceWorkCalculator>();
        builder.Register<V23MaterialSalvageCalculator>(Lifetime.Singleton)
            .As<IMaterialSalvageCalculator>();
        builder.Register<DeterministicCraftQualityResolver>(Lifetime.Singleton)
            .As<ICraftQualityResolver>();
        builder.Register<TextileBatchCompactionService>(Lifetime.Singleton)
            .As<ITextileBatchCompactionService>();
        builder.Register<ApparelPhysicalTransaction>(Lifetime.Singleton)
            .As<IApparelPhysicalTransaction>();
        builder.Register<ApparelWorkOrderRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IApparelWorkOrderCommand>()
            .As<IApparelWorkOrderQuery>()
            .As<IApparelWorkOrderPersistence>()
            .As<IProductionApparelOrderTerminalEffectPort>()
            .As<IProductionApparelOrderSourceTerminalPort>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<CharacterEnvironmentAggregateStateStore>(
            Lifetime.Singleton);
        builder.Register<CharacterApparelAggregateStateStore>(Lifetime.Singleton);
        builder.Register<AnatomyAttachmentQuery>(Lifetime.Singleton)
            .As<IAnatomyAttachmentQuery>();
        builder.Register<ApparelMaterialProjector>(Lifetime.Singleton)
            .As<IApparelMaterialProjector>();
        builder.Register<ApparelAvailabilityIndex>(Lifetime.Singleton)
            .As<IApparelAvailabilityIndex>();
        builder.Register<CharacterApparelAggregate>(Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterApparelQuery>()
            .As<ICharacterApparelCommand>()
            .As<ICharacterApparelPersistence>();
        builder.Register<EquippedApparelPhysicalMassQuery>(Lifetime.Singleton)
            .As<IEquippedApparelPhysicalMassQuery>();
        builder.Register<EnvironmentalWorkwearRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IEnvironmentalWorkwearQuery>()
            .As<IEnvironmentalWorkwearCommand>()
            .As<IEnvironmentalWorkwearPersistence>();
        builder.Register<CharacterEnvironmentProtectionResolver>(
                Lifetime.Singleton)
            .As<ICharacterEnvironmentProtectionResolver>();
        builder.RegisterEntryPoint<CharacterEnvironmentUnityAdapter>(
                Lifetime.Singleton)
            .As<ICharacterEnvironmentStatusQuery>()
            .As<ICharacterEnvironmentExposureCommand>()
            .As<ICharacterEnvironmentWorkContext>()
            .As<ICharacterEnvironmentPersistence>();
        builder.Register<EnvironmentWorkPolicyUnityAdapter>(Lifetime.Singleton)
            .As<IEnvironmentWorkPolicy>();
        builder.Register<EnvironmentalWorkwearProductionOutputHandler>(
                Lifetime.Singleton)
            .As<IProductionOutputHandler>()
            .As<IProductionOutputCapability>();
        builder.Register<
                EnvironmentalWorkwearProductionOutputRestoreCapabilityValidator>(
                Lifetime.Singleton)
            .As<IProductionResolvedOutputRestoreCapabilityValidator>();
        builder.RegisterEntryPoint<IndustrialInfrastructureOverlayPresenter>(
                Lifetime.Singleton)
            .As<IIndustrialInfrastructureOverlayService>();
        if (SampleSceneRationRuntime.SupportsScene(scopeScene.name))
        {
            builder.RegisterEntryPoint<SampleSceneRationRuntime>(
                    Lifetime.Singleton)
                .AsSelf();
        }

        builder.Register<CharacterNeedBalanceRuntime>(Lifetime.Singleton)
            .As<ICharacterNeedBalanceRuntime>();
        builder.Register<CharacterDeprivationStateStore>(Lifetime.Singleton);
        builder.Register<CharacterPrimitiveSurvivalDependencies>(Lifetime.Singleton);
        builder.Register<CharacterDeprivationWorldDependencies>(Lifetime.Singleton);
        builder.Register<CharacterDeprivationSystemDependencies>(Lifetime.Singleton);
        builder.Register<CharacterDeprivationAuthorityDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CharacterDeprivationRuntime>(
                Lifetime.Singleton)
            .As<ICharacterDeprivationRuntime>()
            .As<ICharacterDeprivationQuery>()
            .As<ICharacterDeprivationCommand>()
            .As<ICharacterDeprivationIncidentSink>()
            .As<ICharacterDeprivationPersistence>();
        builder.Register<WorkOrderAggregateStateStore>(Lifetime.Singleton);
        builder.Register<WorkOrderExecutionServices>(Lifetime.Singleton);
        builder.Register<WorkConstructionInputOwnerRuntime>(Lifetime.Singleton)
            .As<IWorkConstructionInputOwnerRuntime>();
        builder.RegisterEntryPoint<WorkOrderRuntime>(Lifetime.Singleton)
            .As<IWorkOrderRuntime>()
            .As<IWorkOrderQuery>()
            .As<IWorkOrderDestructiveDrainRetentionQuery>()
            .As<IWorkOrderWorkerPolicyQuery>()
            .As<IWorkOrderWorkerPolicyCommand>()
            .As<IQualityTargetPipelineQuery>()
            .As<IQualityTargetPipelineCommand>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<ResourceWildlifeSpeciesCatalogProvider>(
                Lifetime.Singleton)
            .As<IWildlifeSpeciesCatalogProvider>();
        builder.RegisterEntryPoint<WildlifeHabitatMarkerRegistry>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeHabitatMarkerQuery>()
            .As<IWildlifeHabitatMarkerRegistry>();
        builder.Register<WildlifeOverlayRootPort>(Lifetime.Singleton)
            .As<IWildlifeOverlayRootPort>();
        builder.Register<WildlifeEcosystemApplicationPorts>(Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeEcosystemWorldPort>()
            .As<IWildlifeEcosystemPresentationPort>();
        builder.Register<WildlifeEcosystemRuntime>(Lifetime.Singleton)
            .AsSelf();
        builder.RegisterEntryPoint<WildlifeEcosystemApplicationAdapter>(
                Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeEcosystemRuntime>();
        builder.Register<WorldResourceEnvironmentPortAdapter>(Lifetime.Singleton)
            .As<IWorldResourceEnvironmentPort>();
        builder.Register<WorldResourceNodeHostPortAdapter>(Lifetime.Singleton)
            .As<IWorldResourceNodeHostPort>();
        builder.Register<BuiltInWorldResourceSourceBindingContributor>(
                Lifetime.Singleton)
            .As<IWorldResourceSourceBindingContributor>();
        builder.Register<WorldResourceSourceBindingCatalog>(Lifetime.Singleton)
            .As<IWorldResourceSourceBindingCatalog>();
        builder.Register<WorldResourceOutputMaximumEnvelopeAuthority>(
                Lifetime.Singleton)
            .As<IWorldResourceOutputMaximumEnvelopeAuthority>();
        builder.Register<WorldResourceOutputPublicationPortAdapter>(Lifetime.Singleton)
            .As<IWorldResourceOutputPublicationPort>();
        builder.Register<WorldResourceResearchPortAdapter>(Lifetime.Singleton)
            .As<IWorldResourceResearchPort>();
        builder.Register<WorldResourceEnvironmentDependencies>(Lifetime.Singleton);
        builder.Register<WorldResourceInfrastructureDependencies>(Lifetime.Singleton);
        builder.Register<WorldResourceProgressionDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WorldResourceRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IWorldResourceRuntime>()
            .As<IWorldResourcePersistence>();
        builder.Register<CropCycleInputRequirementAuthority>(Lifetime.Singleton)
            .As<ICropCycleInputRequirementQuery>();
        builder.Register<CropPlotInputOwnerRuntime>(Lifetime.Singleton)
            .As<ICropPlotInputOwnerRuntime>();
        builder.Register<CropPlotWorldDependencies>(Lifetime.Singleton);
        builder.Register<CropPlotSimulationDependencies>(Lifetime.Singleton);
        builder.Register<PhysicalSeedLotGateway>(Lifetime.Singleton)
            .As<IPhysicalSeedLotGateway>();
        builder.Register<CropEcologyRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICropEcologyService>()
            .As<ICropEcologyHarvestTransactionService>()
            .As<ICropEcologyPersistence>()
            .As<IInitialCropSeedGrant>();
        builder.Register<CertifiedSeedInputOwnerRuntime>(Lifetime.Singleton)
            .As<ICertifiedSeedInputOwnerRuntime>();
        builder.Register<CertifiedSeedRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICertifiedSeedCommand>()
            .As<ICertifiedSeedExecutionReceiptQuery>()
            .As<ICertifiedSeedPersistence>()
            .As<ICertifiedSeedInputOwnerDescriptorSource>()
            .As<IProductionDomainOutputRestoreOwnerSource>()
            .As<IProductionDomainOutputFacilityLifecycleQuery>();
        builder.Register<ProductionDomainOutputRestoreGuard>(Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<CropPhysicalRestoreGuard>(Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<CertifiedSeedApplicationAdapter>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<CropSeedBootstrapRuntime>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CropPlotRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICropPlotRuntime>()
            .As<ICropPlotPersistence>()
            .As<ICropCycleExecutionCorrelationCommand>()
            .As<ICropPlanExecutionReceiptQuery>()
            .As<ICropPlotInputOwnerDescriptorSource>()
            .As<IProductionDomainOutputRestoreOwnerSource>()
            .As<IProductionDomainOutputFacilityLifecycleQuery>();
        builder.Register<WildlifeCarcassService>(Lifetime.Singleton)
            .As<IWildlifeCarcassService>();
        builder.Register<WildlifeWorldServices>(Lifetime.Singleton);
        builder.Register<WildlifeCombatServices>(Lifetime.Singleton);
        builder.Register<WildlifeExecutionServices>(Lifetime.Singleton);
        builder.Register<WildlifeRestoreServices>(Lifetime.Singleton);
        builder.RegisterEntryPoint<WildlifeRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeRuntime>()
            .As<IWildlifeQuery>()
            .As<IWildlifeHuntCommandService>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<WildlifeFoodRaidOutcomeTextLocalizer>(Lifetime.Singleton)
            .As<IWildlifeFoodRaidOutcomeTextQuery>();
        builder.Register<DungeonStory.CoreSession.ExternalInfluenceAggregateStateStore>(
            Lifetime.Singleton);
        builder.Register<ExternalInfluenceRuntimeApplicationAdapter.Dependencies>(
            Lifetime.Singleton);
        builder.RegisterEntryPoint<ExternalInfluenceRuntimeApplicationAdapter>(
                Lifetime.Singleton)
            .As<IExternalInfluenceRuntime>()
            .As<IExternalCombatInfluenceQuery>();
        builder.Register<SurvivalFoodRuntimeDependencies>(Lifetime.Singleton);
        builder.RegisterEntryPoint<SurvivalFoodRuntime>(Lifetime.Singleton)
            .As<ISurvivalFoodQuery>()
            .As<ISurvivalFoodCommand>()
            .As<ISurvivalFoodPersistence>()
            .As<ISurvivalFoodDebugCommand>()
            .As<ICharacterNutritionRuntime>()
            .As<ISurvivalEnvironmentQuery>()
            .As<ISurvivalStorageEnvironmentSink>();
        builder.RegisterEntryPoint<SurvivalEnvironmentalFieldBridge>(
                Lifetime.Singleton)
            .AsSelf();
        builder.Register<CharacterConsumablesApplicationPorts>(Lifetime.Singleton)
            .As<ICharacterConsumablesWorldPort>()
            .As<ICharacterConsumablesInventoryPort>()
            .As<ICharacterConsumablesEventPort>()
            .As<ICharacterConsumablesWorkforcePort>();
        builder.Register<CharacterConsumablesInputOwnerDescriptorSource>(
                Lifetime.Singleton)
            .As<ICharacterConsumablesInputOwnerDescriptorSource>();
        builder.Register<CharacterConsumablesInputOwnerRuntime>(Lifetime.Singleton)
            .As<ICharacterConsumablesInputOwnerRuntime>();
        builder.RegisterEntryPoint<CharacterConsumablesInputOwnerLifecycleRuntime>(
            Lifetime.Singleton);
        builder.Register<CharacterConsumablesRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterConsumablesApplication>()
            .As<ICharacterConsumablesPersistence>();
        builder.RegisterEntryPoint<CharacterConsumablesCompatibilityAdapter>(
                Lifetime.Singleton)
            .As<ICharacterConsumablesQuery>()
            .As<ICharacterConsumablesCommand>()
            .As<IFieldMealConsumptionCommand>()
            .As<ICharacterDietPolicyRuntime>()
            .As<IMealConsumptionRuntime>()
            .As<ICharacterMealOperationCancellation>()
            .As<ICharacterSubstanceRuntime>();
        builder.Register<CaptivityPersuasionHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityIsolationHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityCoercionHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityInterrogationHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityIndoctrinationHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityBrandingHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityBloodExtractionHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityMemoryExtractionHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityForcedModificationHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityCorruptionRitualHandler>(Lifetime.Singleton)
            .As<ICaptivityInteractionHandler>();
        builder.Register<CaptivityInteractionRegistry>(Lifetime.Singleton);
        builder.Register<CaptivityInteractionMaterialMassCatalog>(
                Lifetime.Singleton)
            .As<ICaptivityInteractionMaterialMassCatalog>();
        builder.Register<CaptivityInteractionMaterialRuntime>(
                Lifetime.Singleton)
            .AsSelf()
            .As<ICaptivityInteractionMaterialRuntime>();
        builder.Register<CaptivityCharacterContext>(Lifetime.Singleton);
        builder.Register<CaptivityWorldContext>(Lifetime.Singleton);
        builder.Register<CaptivitySessionContext>(Lifetime.Singleton);
        builder.Register<CaptivityCareLaborInputOwnerRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<ICaptivityCareLaborInputOwnerRuntime>();
        builder.RegisterEntryPoint<CaptivityRuntime>(Lifetime.Singleton)
            .As<ICaptivityRuntime>()
            .As<ICaptivityRestoreStateQuery>()
            .As<ICaptivityPersistence>()
            .As<ICaptiveLaborQuery>()
            .As<ICaptivityWorkReadinessQuery>()
            .As<ICaptivityCommandService>()
            .As<ICaptivityEscortRuntime>()
            .As<ICaptivityEscapeRuntime>()
            .As<IMinionSettlementCommand>()
            .As<ICharacterCarePriorityQuery>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<MinionSettlementSocialRuntime>(
            Lifetime.Singleton);
        builder.Register<CaptivityCareLaborInputOwnerRestoreParticipant>(
                Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<CaptivityInteractionMaterialLifecycleRuntime>(
                Lifetime.Singleton)
            .AsSelf()
            .As<ICaptivityInteractionMaterialRestoreAuthority>();
        builder.Register<CaptivityInteractionMaterialRestoreParticipant>(
                Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.Register<CaptivityRetaliationEffectsAdapter>(Lifetime.Singleton)
            .As<ICaptivityRetaliationEffectsPort>();
        builder.RegisterEntryPoint<CaptivityRetaliationRuntime>(Lifetime.Singleton)
            .AsSelf();
        builder.Register<WildlifeCaptureWorldContext>(Lifetime.Singleton);
        builder.Register<WildlifeCaptureCareContext>(Lifetime.Singleton);
        builder.Register<WildlifeCaptureSessionContext>(Lifetime.Singleton);
        builder.Register<WildlifeCareInputOwnerSource>(Lifetime.Singleton)
            .As<IWildlifeCareInputOwnerSource>();
        builder.Register<WildlifeCareInputOwnerRuntime>(Lifetime.Singleton)
            .AsSelf()
            .As<IWildlifeCareInputOwnerRuntime>();
        builder.RegisterEntryPoint<WildlifeCareInputOwnerLifecycleRuntime>(
                Lifetime.Singleton)
            .As<IDungeonSaveCaptureGuard>();
        builder.Register<WildlifeCareInputOwnerRestoreParticipant>(
                Lifetime.Singleton)
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<WildlifeCaptureRuntime>(Lifetime.Singleton)
            .As<IWildlifeCaptureRuntime>()
            .As<IWildlifeCaptureTransportRuntime>();
        builder.RegisterEntryPoint<AnimalHusbandryRuntime>(Lifetime.Singleton)
            .As<IAnimalHusbandryQuery>()
            .As<IAnimalHusbandryCommand>()
            .As<IAnimalHusbandryPersistence>()
            .As<IAnimalPenCompatibilityQuery>();
        builder.Register<NonlethalActCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<TrophyDisplayCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<DangerousStuntCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<CaptiveDuelCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<BeastShowCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<BeastArenaCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<PublicPunishmentCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<ExecutionPlayCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<PublicCorruptionRitualCircusProgram>(Lifetime.Singleton)
            .As<ICircusProgramHandler>();
        builder.Register<CircusProgramRegistry>(Lifetime.Singleton);
        builder.Register<CircusPerformanceSupplyRuntime>(Lifetime.Singleton);
        builder.Register<CircusProgramContext>(Lifetime.Singleton);
        builder.Register<CircusWorldContext>(Lifetime.Singleton);
        builder.Register<CircusCombatContext>(Lifetime.Singleton);
        builder.Register<CircusSessionContext>(Lifetime.Singleton);
        builder.RegisterEntryPoint<CircusRuntime>(Lifetime.Singleton)
            .As<ICircusRuntime>()
            .As<ICircusPersistence>()
            .As<IDungeonRestoreTransactionParticipant>();
        builder.RegisterEntryPoint<ItemStackViewToggleRuntime>(
                Lifetime.Singleton)
            .AsSelf();
        builder.RegisterEntryPoint<WildlifeEcosystemViewToggleRuntime>(
                Lifetime.Singleton)
            .AsSelf();
    }
}
